// GENERATED by tools/icons/gen_icons.py — do not edit by hand.
// Phosphor Icons (MIT), fonts bundled in assets/fonts/phosphor.

import 'package:flutter/widgets.dart';

abstract final class PhosphorIconsRegular {
  static const arrowCounterClockwise = IconData(
    0xe038,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const arrowsClockwise = IconData(
    0xe094,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const bell = IconData(
    0xe0ce,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const bookOpen = IconData(
    0xe0e6,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const bookOpenText = IconData(
    0xe8f2,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const bookmarkSimple = IconData(
    0xe0ea,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const bookmarksSimple = IconData(
    0xe5f0,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const calendar = IconData(
    0xe108,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const calendarBlank = IconData(
    0xe10a,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const calendarCheck = IconData(
    0xe712,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const caretDown = IconData(
    0xe136,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const caretRight = IconData(
    0xe13a,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const clock = IconData(
    0xe19a,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const clockCounterClockwise = IconData(
    0xe1a0,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const cloudArrowUp = IconData(
    0xe1ae,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const cloudSlash = IconData(
    0xe1b6,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const copy = IconData(
    0xe1ca,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const eraser = IconData(
    0xe21e,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const eye = IconData(
    0xe220,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const eyeSlash = IconData(
    0xe224,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const flask = IconData(
    0xe79e,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const gearSix = IconData(
    0xe272,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const handsPraying = IconData(
    0xecc8,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const headphones = IconData(
    0xe2a6,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const heart = IconData(
    0xe2a8,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const highlighter = IconData(
    0xec76,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const house = IconData(
    0xe2c2,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const image = IconData(
    0xe2ca,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const info = IconData(
    0xe2ce,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const lockSimple = IconData(
    0xe308,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const magnifyingGlass = IconData(
    0xe30c,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const notePencil = IconData(
    0xe34c,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const notebook = IconData(
    0xe34e,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const pencilSimple = IconData(
    0xe3b4,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const plusCircle = IconData(
    0xe3d6,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const shareNetwork = IconData(
    0xe408,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const signIn = IconData(
    0xe428,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const signOut = IconData(
    0xe42a,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const textAa = IconData(
    0xe6ee,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const textAlignCenter = IconData(
    0xe480,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const textAlignJustify = IconData(
    0xe482,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const textAlignLeft = IconData(
    0xe484,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const translate = IconData(
    0xe4a2,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const trash = IconData(
    0xe4a6,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const user = IconData(
    0xe4c2,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const userCircle = IconData(
    0xe4c4,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
  static const xCircle = IconData(
    0xe4f8,
    fontFamily: 'PhosphorRegular',
    matchTextDirection: true,
  );
}

abstract final class PhosphorIconsBold {
  static const arrowBendDownRight = IconData(
    0xe01a,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const arrowRight = IconData(
    0xe06c,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const caretDown = IconData(
    0xe136,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const caretLeft = IconData(
    0xe138,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const caretRight = IconData(
    0xe13a,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const check = IconData(
    0xe182,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const checkCircle = IconData(
    0xe184,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const dotsThree = IconData(
    0xe1fe,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const googleLogo = IconData(
    0xe292,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const play = IconData(
    0xe3d0,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const plus = IconData(
    0xe3d4,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const shareNetwork = IconData(
    0xe408,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const sparkle = IconData(
    0xe6a2,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
  static const x = IconData(
    0xe4f6,
    fontFamily: 'PhosphorBold',
    matchTextDirection: true,
  );
}

abstract final class PhosphorIconsFill {
  static const bookOpenText = IconData(
    0xe8f2,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const bookmarkSimple = IconData(
    0xe0ea,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const calendarCheck = IconData(
    0xe712,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const checkCircle = IconData(
    0xe184,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const handsPraying = IconData(
    0xecc8,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const house = IconData(
    0xe2c2,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const notePencil = IconData(
    0xe34c,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const pause = IconData(
    0xe39e,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const play = IconData(
    0xe3d0,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const skipBack = IconData(
    0xe5a4,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const skipForward = IconData(
    0xe5a6,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const sparkle = IconData(
    0xe6a2,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
  static const user = IconData(
    0xe4c2,
    fontFamily: 'PhosphorFill',
    matchTextDirection: true,
  );
}
