#!/usr/bin/env sh
# Builds supabase/setup_all.sql = schema migration + seed + a check query, so
# the whole database can be set up with ONE paste into the Supabase SQL Editor
# (handy on a phone). Re-run after changing the migration or seed.
set -e
cd "$(dirname "$0")/.."
{
  echo "-- BODYFORGE one-step setup. GENERATED by tool/build_setup_sql.sh — do not edit by hand."
  echo "-- Paste into Supabase → SQL Editor → Run. Safe to run again; never drops or overwrites data."
  echo
  cat supabase/migrations/20260928000001_bodyforge_schema.sql
  echo
  cat supabase/seed.sql
  echo
  echo "-- Check: this should show exercises 114, skill_nodes 54, foods 32, challenges 4, achievements 23."
  echo "select (select count(*) from public.exercises) as exercises,"
  echo "       (select count(*) from public.skill_nodes) as skill_nodes,"
  echo "       (select count(*) from public.nutrition_items) as foods,"
  echo "       (select count(*) from public.challenges) as challenges,"
  echo "       (select count(*) from public.achievements) as achievements,"
  echo "       'BODYFORGE database ready' as status;"
} > supabase/setup_all.sql
echo "wrote supabase/setup_all.sql"
