// Generates supabase/seed.sql from the in-app catalogs so the server's
// reference data always matches what ships in the app.
//
//   dart run tool/generate_seed.dart
//
// The output only INSERTs / UPSERTs reference rows (on conflict do update);
// it never deletes anything.
import 'dart:io';

import 'package:bodyforge/domain/catalog/achievements.dart';
import 'package:bodyforge/domain/catalog/challenges.dart';
import 'package:bodyforge/domain/catalog/exercises.dart';
import 'package:bodyforge/domain/catalog/foods.dart';
import 'package:bodyforge/domain/catalog/skill_paths.dart';

String q(String? s) => s == null ? 'null' : "'${s.replaceAll("'", "''")}'";
String arr(Iterable<String> xs) => xs.isEmpty ? "'{}'::text[]" : 'array[${xs.map(q).join(', ')}]::text[]';
String b(bool v) => v ? 'true' : 'false';
String n(num v) => v is int ? '$v' : v.toString();

String upsert(String table, List<String> cols, List<List<String>> rows) {
  if (rows.isEmpty) return '';
  final set = cols.where((c) => c != 'id').map((c) => '$c = excluded.$c').join(',\n  ');
  final values = rows.map((r) => '  (${r.join(', ')})').join(',\n');
  return 'insert into public.$table (${cols.join(', ')}) values\n$values\non conflict (id) do update set\n  $set;\n\n';
}

void main() {
  final out = StringBuffer()
    ..writeln('-- GENERATED by tool/generate_seed.dart — do not edit by hand.')
    ..writeln('-- Reference data for BODYFORGE. Idempotent: safe to run again after updates.')
    ..writeln('begin;')
    ..writeln();

  out.write(upsert('exercises', [
    'id', 'name', 'area', 'pattern', 'focus', 'difficulty', 'unit', 'per_side', 'space', 'impact', 'floor_work',
    'knee_stress', 'wrist_stress', 'props', 'seconds_per_rep', 'family', 'mobility', 'warmup', 'demo', 'summary',
    'cues', 'mistakes'
  ], [
    for (final e in kExercises)
      [
        q(e.id), q(e.name), q(e.area.name), q(e.pattern.name), arr(e.focus.map((f) => f.name)), n(e.difficulty),
        q(e.unit.name), b(e.perSide), q(e.space.name), b(e.impact), b(e.floorWork), b(e.kneeStress),
        b(e.wristStress), arr(e.props.map((p) => p.name)), n(e.secondsPerRep), q(e.family), b(e.mobility),
        b(e.warmup), q(e.demo), q(e.summary), arr(e.cues), arr(e.mistakes),
      ]
  ]));

  out.write(upsert('skill_paths', ['id', 'name', 'area', 'goal_label', 'rep_min', 'rep_max', 'hold_min', 'hold_max', 'sort'], [
    for (var i = 0; i < kSkillPaths.length; i++)
      () {
        final p = kSkillPaths[i];
        return [q(p.id), q(p.name), q(p.area.name), q(p.goalLabel), n(p.repRange.$1), n(p.repRange.$2),
          n(p.holdRange.$1), n(p.holdRange.$2), n(i)];
      }()
  ]));

  out.write(upsert('skill_nodes', ['id', 'path_id', 'position', 'exercise_id', 'alternatives', 'milestone'], [
    for (final p in kSkillPaths)
      for (var i = 0; i < p.nodes.length; i++)
        [q('${p.id}:$i'), q(p.id), n(i), q(p.nodes[i].exerciseId), arr(p.nodes[i].alternatives), b(p.nodes[i].milestone)]
  ]));

  out.write(upsert('nutrition_items',
      ['id', 'name', 'aka', 'category', 'serving', 'kcal', 'protein', 'carbs', 'fat', 'price_ghs', 'tips'], [
    for (final f in kFoods)
      [q(f.id), q(f.name), q(f.aka), q(f.category.name), q(f.serving), n(f.kcal), n(f.protein), n(f.carbs),
        n(f.fat), n(f.priceGhs), arr(f.tips)]
  ]));

  out.write(upsert('challenges', [
    'id', 'title', 'tagline', 'description', 'daily_prompt', 'check_type', 'days_required', 'daily_target',
    'protein_target', 'price_limit_ghs', 'tips'
  ], [
    for (final c in kChallenges)
      [q(c.id), q(c.title), q(c.tagline), q(c.description), q(c.dailyPrompt), q(c.checkType.name),
        n(c.daysRequired), n(c.dailyTarget), n(c.proteinTarget), n(c.priceLimitGhs), arr(c.tips)]
  ]));

  out.write(upsert('achievements', ['id', 'title', 'description', 'tier', 'icon', 'target'], [
    for (final a in kAchievements) [q(a.id), q(a.title), q(a.description), q(a.tier.name), q(a.icon), n(a.target)]
  ]));

  out.writeln('commit;');
  final file = File('supabase/seed.sql')..writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${file.path}: ${kExercises.length} exercises, ${kSkillPaths.length} paths, '
      '${kFoods.length} foods, ${kChallenges.length} challenges, ${kAchievements.length} achievements.');
}
