// GENERATED by tool/prepare_assets.py — do not edit.
// Background colours sampled from each illustration, so the card
// behind an image matches its edges exactly.

const Map<String, int> kIllustrationBackgrounds = {
  'app_icon': 0xFFA38FEE,
  'app_icon_background': 0xFFA18DEC,
  'collection_butter': 0xFFF4D46F,
  'collection_lavender': 0xFF9D8BEA,
  'collection_lime': 0xFFD4E972,
  'collection_mint': 0xFFB2E1C7,
  'collection_peach': 0xFFF5AA81,
  'collection_sky': 0xFFA2C5ED,
  'empty_bookmarks': 0xFFD5F0E1,
  'empty_collections': 0xFFF9DFE4,
  'empty_highlights': 0xFFF6E8B7,
  'empty_history': 0xFFDBE7F8,
  'empty_library': 0xFFDED7F8,
  'empty_notes': 0xFFF9E3D5,
  'empty_search': 0xFFEBE3D6,
  'onboarding_habit': 0xFFFBDAC7,
  'onboarding_highlight': 0xFFE9F4B2,
  'onboarding_library': 0xFFE5DFF9,
  'session_complete': 0xFFEBF2C7,
};
