#!/usr/bin/env python3
"""Writes lib/core/icons.dart: the Phosphor icons the app uses, as plain
IconData constants on the bundled Phosphor fonts (assets/fonts/phosphor).

phosphor_flutter 2.1.0 subclasses IconData, which newer Flutter versions
forbid (IconData is final), so the package's classes can't be compiled
for web. Code points are read from the package source in the pub cache.
Re-run after using a new icon (needs the package source in the pub cache:
`dart pub cache add phosphor_flutter --version 2.1.0`):
    python3 tools/icons/gen_icons.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PUB = Path.home() / ".pub-cache/hosted/pub.dev/phosphor_flutter-2.1.0/lib/src"
STYLES = {"Regular": "PhosphorRegular", "Bold": "PhosphorBold", "Fill": "PhosphorFill"}

used: dict[str, set[str]] = {s: set() for s in STYLES}
for f in (ROOT / "lib").rglob("*.dart"):
    if f.name == "icons.dart":
        continue
    for style, name in re.findall(r"PhosphorIcons(Regular|Bold|Fill)\.(\w+)", f.read_text()):
        used[style].add(name)

out = [
    "// GENERATED by tools/icons/gen_icons.py — do not edit by hand.",
    "// Phosphor Icons (MIT), fonts bundled in assets/fonts/phosphor.",
    "",
    "import 'package:flutter/widgets.dart';",
    "",
]
for style, family in STYLES.items():
    src = (PUB / f"phosphor_icons_{style.lower()}.dart").read_text()
    codes = dict(re.findall(r"static const (\w+) = Phosphor\w*IconData\((0x[0-9a-f]+), '" + style + "'\)", src))
    out.append(f"abstract final class PhosphorIcons{style} {{")
    for name in sorted(used[style]):
        if name not in codes:
            raise SystemExit(f"Unknown Phosphor {style} icon: {name}")
        out.append(
            f"  static const {name} = IconData({codes[name]}, "
            f"fontFamily: '{family}', matchTextDirection: true);"
        )
    out.append("}")
    out.append("")
(ROOT / "lib" / "core" / "icons.dart").write_text("\n".join(out))
print("icons:", {s: len(n) for s, n in used.items()})
