import 'package:flutter/material.dart';

/// One icon vocabulary (rounded, bold) used everywhere.
abstract final class BfIcons {
  static const home = Icons.home_rounded;
  static const homeOutline = Icons.home_outlined;
  static const workout = Icons.bolt_rounded;
  static const workoutOutline = Icons.bolt_outlined;
  static const progress = Icons.insights_rounded;
  static const progressOutline = Icons.insights_outlined;
  static const nutrition = Icons.restaurant_rounded;
  static const nutritionOutline = Icons.restaurant_outlined;
  static const profile = Icons.person_rounded;
  static const profileOutline = Icons.person_outline_rounded;

  static const back = Icons.arrow_back_rounded;
  static const forward = Icons.arrow_forward_rounded;
  static const chevronRight = Icons.chevron_right_rounded;
  static const chevronLeft = Icons.chevron_left_rounded;
  static const close = Icons.close_rounded;
  static const check = Icons.check_rounded;
  static const add = Icons.add_rounded;
  static const remove = Icons.remove_rounded;
  static const edit = Icons.edit_rounded;
  static const delete = Icons.delete_outline_rounded;
  static const settings = Icons.settings_rounded;
  static const play = Icons.play_arrow_rounded;
  static const pause = Icons.pause_rounded;
  static const skip = Icons.skip_next_rounded;
  static const swap = Icons.swap_horiz_rounded;
  static const timer = Icons.timer_outlined;
  static const info = Icons.info_outline_rounded;
  static const search = Icons.search_rounded;
  static const filter = Icons.tune_rounded;
  static const calendar = Icons.calendar_month_rounded;
  static const bolt = Icons.bolt_rounded;
  static const flame = Icons.local_fire_department_rounded;
  static const trophy = Icons.emoji_events_rounded;
  static const lock = Icons.lock_rounded;
  static const unlock = Icons.lock_open_rounded;
  static const leaf = Icons.spa_rounded;
  static const moon = Icons.bedtime_rounded;
  static const sore = Icons.healing_rounded;
  static const energy = Icons.battery_charging_full_rounded;
  static const cloud = Icons.cloud_done_rounded;
  static const cloudOff = Icons.cloud_off_rounded;
  static const sync = Icons.sync_rounded;
  static const localOnly = Icons.phone_iphone_rounded;
  static const drop = Icons.water_drop_rounded;
  static const food = Icons.egg_alt_rounded;
  static const ruler = Icons.straighten_rounded;
  static const scale = Icons.monitor_weight_rounded;
  static const flag = Icons.flag_rounded;
  static const map = Icons.route_rounded;
  static const star = Icons.star_rounded;
  static const reset = Icons.refresh_rounded;
  static const export = Icons.ios_share_rounded;
  static const bell = Icons.notifications_rounded;
  static const theme = Icons.contrast_rounded;
  static const units = Icons.square_foot_rounded;
  static const vibration = Icons.vibration_rounded;
  static const logout = Icons.logout_rounded;
  static const warning = Icons.warning_amber_rounded;
  static const location = Icons.place_rounded;
  static const hexagon = Icons.hexagon_rounded;
  static const radioOn = Icons.radio_button_checked_rounded;
  static const radioOff = Icons.radio_button_unchecked_rounded;
  static const checkBoxOn = Icons.check_circle_rounded;
  static const checkBoxOff = Icons.circle_outlined;
  static const time = Icons.schedule_rounded;
  static const tip = Icons.lightbulb_rounded;
  static const volume = Icons.graphic_eq_rounded;
  static const up = Icons.trending_up_rounded;
  static const down = Icons.trending_down_rounded;
  static const flat = Icons.trending_flat_rounded;
  static const plus15 = Icons.more_time_rounded;
  static const build = Icons.construction_rounded;
  static const library = Icons.menu_book_rounded;
  static const tree = Icons.account_tree_rounded;
  static const plan = Icons.view_week_rounded;
  static const test = Icons.speed_rounded;
  static const user = Icons.account_circle_rounded;
  static const heart = Icons.favorite_rounded;

  static IconData forAchievement(String key) => switch (key) {
        'bolt' => bolt,
        'calendar' => calendar,
        'trophy' => trophy,
        'push' => Icons.fitness_center_rounded,
        'flame' => flame,
        'core' => Icons.center_focus_strong_rounded,
        'crown' => Icons.workspace_premium_rounded,
        'unlock' => unlock,
        'summit' => Icons.landscape_rounded,
        'legs' => Icons.directions_run_rounded,
        'timer' => Icons.timer_rounded,
        'spark' => Icons.auto_awesome_rounded,
        'leaf' => leaf,
        'return' => Icons.replay_rounded,
        'flag' => flag,
        'half' => Icons.contrast_rounded,
        'ruler' => ruler,
        'drop' => drop,
        'food' => food,
        _ => star,
      };
}
