-- BODYFORGE one-step setup. GENERATED by tool/build_setup_sql.sh — do not edit by hand.
-- Paste into Supabase → SQL Editor → Run. Safe to run again; never drops or overwrites data.

-- BODYFORGE schema
-- Reference data (read-only for users) + user-owned tables protected by RLS.
-- Column names match the app's local SQLite schema 1:1 (lib/data/local/tables.dart)
-- so offline changes sync without translation.
--
-- Safe to run on a fresh project. It only CREATEs objects (IF NOT EXISTS where
-- possible) and never drops or truncates anything.

-- ─────────────────────────────────────────────────────────────────────────────
-- Safety guard: refuse to run on a project that already has same-named
-- objects BODYFORGE didn't create (e.g. another app's `profiles` table).
-- Nothing is changed if this check fails. Re-running on a BODYFORGE database
-- is fine: every object below is labelled with a 'BODYFORGE' comment.
-- ─────────────────────────────────────────────────────────────────────────────
do $guard$
declare
  t text;
  clashes text[] := '{}';
begin
  foreach t in array array['exercises', 'skill_paths', 'skill_nodes', 'nutrition_items', 'challenges', 'achievements', 'profiles', 'goals', 'programs', 'program_days', 'workouts', 'workout_sets', 'personal_records', 'measurements', 'skill_progress', 'recovery_checks', 'challenge_progress', 'challenge_checkins', 'user_achievements', 'journey_progress', 'milestones', 'food_prices', 'sync_metadata'] loop
    if to_regclass('public.' || t) is not null
       and coalesce(obj_description(to_regclass('public.' || t), 'pg_class'), '') not like 'BODYFORGE%' then
      clashes := clashes || ('table public.' || t);
    end if;
  end loop;
  if to_regprocedure('public.delete_my_account()') is not null
     and coalesce(obj_description(to_regprocedure('public.delete_my_account()'), 'pg_proc'), '') not like 'BODYFORGE%' then
    clashes := clashes || 'function public.delete_my_account()'::text;
  end if;
  if array_length(clashes, 1) > 0 then
    raise exception 'BODYFORGE migration stopped: these already exist and were not created by BODYFORGE: %. Use a new, empty Supabase project for BODYFORGE.', array_to_string(clashes, ', ');
  end if;
end
$guard$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Helpers
-- ─────────────────────────────────────────────────────────────────────────────

-- Server-side sync stamp. Clients pull "rows with synced_at > my cursor", so a
-- row pushed late with an old client timestamp is still picked up by others.
create or replace function public.bf_set_synced_at()
returns trigger
language plpgsql
as $$
begin
  new.synced_at := clock_timestamp();
  return new;
end;
$$;

-- Last-write-wins guard: an update carrying an older updated_at than the row
-- already on the server is ignored (the newer row stays, and clients pull it).
create or replace function public.bf_last_write_wins()
returns trigger
language plpgsql
as $$
begin
  if new.updated_at < old.updated_at then
    return null; -- skip this update
  end if;
  return new;
end;
$$;

-- Achievements keep the earliest unlock time when two devices unlocked the same one.
create or replace function public.bf_keep_earliest_unlock()
returns trigger
language plpgsql
as $$
begin
  new.unlocked_at := least(old.unlocked_at, new.unlocked_at);
  return new;
end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Reference data (seeded by supabase/seed.sql; users can only read)
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.exercises (
  id text primary key,
  name text not null,
  area text not null,
  pattern text not null,
  focus text[] not null default '{}',
  difficulty smallint not null check (difficulty between 1 and 10),
  unit text not null check (unit in ('reps', 'seconds')),
  per_side boolean not null default false,
  space text not null check (space in ('small', 'medium', 'large')),
  impact boolean not null default false,
  floor_work boolean not null default true,
  knee_stress boolean not null default false,
  wrist_stress boolean not null default false,
  props text[] not null default '{}',
  seconds_per_rep numeric(4,1) not null default 3,
  family text,
  mobility boolean not null default false,
  warmup boolean not null default false,
  demo text not null,
  summary text not null default '',
  cues text[] not null default '{}',
  mistakes text[] not null default '{}'
);

create table if not exists public.skill_paths (
  id text primary key,
  name text not null,
  area text not null,
  goal_label text not null,
  rep_min smallint not null,
  rep_max smallint not null,
  hold_min smallint not null,
  hold_max smallint not null,
  sort smallint not null default 0
);

create table if not exists public.skill_nodes (
  id text primary key,                      -- '<path_id>:<position>'
  path_id text not null references public.skill_paths(id),
  position smallint not null,
  exercise_id text not null references public.exercises(id),
  alternatives text[] not null default '{}',
  milestone boolean not null default false,
  unique (path_id, position)
);

create table if not exists public.nutrition_items (
  id text primary key,
  name text not null,
  aka text,
  category text not null,
  serving text not null,
  kcal integer not null,
  protein numeric(5,1) not null,
  carbs numeric(5,1) not null,
  fat numeric(5,1) not null,
  price_ghs numeric(7,2) not null,
  tips text[] not null default '{}'
);

create table if not exists public.challenges (
  id text primary key,
  title text not null,
  tagline text not null,
  description text not null,
  daily_prompt text not null,
  check_type text not null,
  days_required smallint not null default 7,
  daily_target smallint not null default 1,
  protein_target numeric(5,1) not null default 0,
  price_limit_ghs numeric(7,2) not null default 0,
  tips text[] not null default '{}'
);

create table if not exists public.achievements (
  id text primary key,
  title text not null,
  description text not null,
  tier text not null,
  icon text not null,
  target integer not null default 1
);

-- ─────────────────────────────────────────────────────────────────────────────
-- User-owned tables. Every one has: id, user_id, created_at, updated_at,
-- deleted_at (soft delete, so deletions sync) and synced_at (server stamp).
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.profiles (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  name text not null,
  age integer not null check (age between 16 and 100),
  sex text not null,
  height_cm double precision not null,
  weight_kg double precision not null,
  fitness_level text not null,
  experience text not null,
  days_per_week integer not null check (days_per_week between 1 and 7),
  session_minutes integer not null check (session_minutes between 5 and 90),
  environment text not null,
  limitations text not null default '{}',
  preferred_days text not null default '[]',
  workout_style text not null,
  push_ability text not null,
  squat_ability text not null,
  plank_ability text not null,
  journey_start date not null,
  constraint profiles_id_is_user check (id = user_id::text)
);

create table if not exists public.goals (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  goal text not null
);

create table if not exists public.programs (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  name text not null,
  source text not null check (source in ('generated', 'custom')),
  goals text not null,
  days_per_week integer not null,
  minutes integer not null,
  focus text not null default '[]',
  active boolean not null default true,
  started_on date not null
);

create table if not exists public.program_days (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  program_id text not null,
  weekday integer not null check (weekday between 1 and 7),
  day_type text not null
);

create table if not exists public.workouts (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  program_id text,
  date date not null,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  day_type text not null,
  kind text not null,
  title text not null,
  plan text not null,
  rating text check (rating in ('tooEasy', 'good', 'hard', 'brutal')),
  duration_sec integer not null,
  total_reps integer not null default 0,
  journey_week integer,
  recovery_check_id text
);

create table if not exists public.workout_sets (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  workout_id text not null,
  exercise_id text not null,
  track_key text,
  block text not null,
  set_index integer not null,
  target integer not null,
  achieved integer not null,
  skipped boolean not null default false,
  completed_at timestamptz
);

create table if not exists public.personal_records (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  exercise_id text not null,
  metric text not null check (metric in ('maxReps', 'maxHold')),
  value integer not null,
  previous_value integer,
  workout_id text,
  achieved_on date not null
);

create table if not exists public.measurements (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  type text not null,
  label text,
  value double precision not null check (value > 0),
  measured_on date not null
);

create table if not exists public.skill_progress (
  id text primary key,                      -- '<user_id>:<track_key>'
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  track_key text not null,
  node_index integer not null,
  sets integer not null,
  amount integer not null,
  easy_streak integer not null default 0,
  hard_streak integer not null default 0,
  best_node integer
);

create table if not exists public.recovery_checks (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  date date not null,
  sleep text not null,
  soreness text not null,
  energy text not null,
  score integer not null,
  mode text not null
);

create table if not exists public.challenge_progress (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  challenge_id text not null,
  started_on date not null,
  completed_on date,
  abandoned boolean not null default false
);

create table if not exists public.challenge_checkins (
  id text primary key,                      -- '<progress_id>:<date>'
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  progress_id text not null,
  date date not null,
  value double precision not null,
  detail text
);

create table if not exists public.user_achievements (
  id text primary key,                      -- '<user_id>:<achievement_id>'
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  achievement_id text not null,
  unlocked_at timestamptz not null
);

create table if not exists public.journey_progress (
  id text primary key,                      -- = user_id
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  start_date date not null,
  current_week integer not null,
  counted_weeks integer not null,
  completed_on date,
  start_nodes text not null default '{}'
);

create table if not exists public.milestones (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  date date not null,
  type text not null,
  title text not null,
  track_key text,
  exercise_id text
);

create table if not exists public.food_prices (
  id text primary key,                      -- '<user_id>:<food_id>'
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null,
  deleted_at timestamptz,
  synced_at timestamptz not null default now(),
  food_id text not null,
  price double precision not null check (price >= 0)
);

-- One row per device: last successful sync, for support/debugging.
create table if not exists public.sync_metadata (
  id text primary key,                      -- '<user_id>:<install_id>'
  user_id uuid not null references auth.users(id) on delete cascade,
  device_label text,
  app_version text,
  last_synced_at timestamptz not null default now(),
  pending_changes integer not null default 0
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Triggers, indexes and Row Level Security for every user table
-- ─────────────────────────────────────────────────────────────────────────────

do $$
declare
  t text;
  user_tables text[] := array[
    'profiles', 'goals', 'programs', 'program_days', 'workouts', 'workout_sets',
    'personal_records', 'measurements', 'skill_progress', 'recovery_checks',
    'challenge_progress', 'challenge_checkins', 'user_achievements',
    'journey_progress', 'milestones', 'food_prices'
  ];
begin
  foreach t in array user_tables loop
    execute format('drop trigger if exists %I on public.%I', 'bf_synced_at_' || t, t);
    execute format(
      'create trigger %I before insert or update on public.%I for each row execute function public.bf_set_synced_at()',
      'bf_synced_at_' || t, t);

    execute format('drop trigger if exists %I on public.%I', 'bf_lww_' || t, t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.bf_last_write_wins()',
      'bf_lww_' || t, t);

    execute format('create index if not exists %I on public.%I (user_id, synced_at)', t || '_user_synced_idx', t);

    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists "Own rows: select" on public.%I', t);
    execute format('create policy "Own rows: select" on public.%I for select to authenticated using ((select auth.uid()) = user_id)', t);
    execute format('drop policy if exists "Own rows: insert" on public.%I', t);
    execute format('create policy "Own rows: insert" on public.%I for insert to authenticated with check ((select auth.uid()) = user_id)', t);
    execute format('drop policy if exists "Own rows: update" on public.%I', t);
    execute format('create policy "Own rows: update" on public.%I for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', t);
    execute format('drop policy if exists "Own rows: delete" on public.%I', t);
    execute format('create policy "Own rows: delete" on public.%I for delete to authenticated using ((select auth.uid()) = user_id)', t);
  end loop;
end;
$$;

drop trigger if exists bf_keep_earliest_unlock on public.user_achievements;
create trigger bf_keep_earliest_unlock
  before update on public.user_achievements
  for each row execute function public.bf_keep_earliest_unlock();

-- sync_metadata: own rows only.
alter table public.sync_metadata enable row level security;
drop policy if exists "Own rows: all" on public.sync_metadata;
create policy "Own rows: all" on public.sync_metadata for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

-- Reference data: readable by everyone, writable by nobody through the API
-- (no insert/update/delete policies; only the SQL editor / seed can write).
do $$
declare
  t text;
  ref_tables text[] := array['exercises', 'skill_paths', 'skill_nodes', 'nutrition_items', 'challenges', 'achievements'];
begin
  foreach t in array ref_tables loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "Reference data: read" on public.%I', t);
    execute format('create policy "Reference data: read" on public.%I for select to anon, authenticated using (true)', t);
  end loop;
end;
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Account deletion (Settings → Delete account). Runs with definer rights but
-- can only ever delete the caller: every user table cascades from auth.users.
-- ─────────────────────────────────────────────────────────────────────────────

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'Not signed in';
  end if;
  delete from auth.users where id = uid;
end;
$$;

revoke all on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- Labels (used by the safety guard at the top when re-running)
-- ─────────────────────────────────────────────────────────────────────────────
comment on table public.exercises is 'BODYFORGE';
comment on table public.skill_paths is 'BODYFORGE';
comment on table public.skill_nodes is 'BODYFORGE';
comment on table public.nutrition_items is 'BODYFORGE';
comment on table public.challenges is 'BODYFORGE';
comment on table public.achievements is 'BODYFORGE';
comment on table public.profiles is 'BODYFORGE';
comment on table public.goals is 'BODYFORGE';
comment on table public.programs is 'BODYFORGE';
comment on table public.program_days is 'BODYFORGE';
comment on table public.workouts is 'BODYFORGE';
comment on table public.workout_sets is 'BODYFORGE';
comment on table public.personal_records is 'BODYFORGE';
comment on table public.measurements is 'BODYFORGE';
comment on table public.skill_progress is 'BODYFORGE';
comment on table public.recovery_checks is 'BODYFORGE';
comment on table public.challenge_progress is 'BODYFORGE';
comment on table public.challenge_checkins is 'BODYFORGE';
comment on table public.user_achievements is 'BODYFORGE';
comment on table public.journey_progress is 'BODYFORGE';
comment on table public.milestones is 'BODYFORGE';
comment on table public.food_prices is 'BODYFORGE';
comment on table public.sync_metadata is 'BODYFORGE';
comment on function public.delete_my_account() is 'BODYFORGE: deletes the signed-in user and (by cascade) all their data';

-- GENERATED by tool/generate_seed.dart — do not edit by hand.
-- Reference data for BODYFORGE. Idempotent: safe to run again after updates.
begin;

insert into public.exercises (id, name, area, pattern, focus, difficulty, unit, per_side, space, impact, floor_work, knee_stress, wrist_stress, props, seconds_per_rep, family, mobility, warmup, demo, summary, cues, mistakes) values
  ('wall_push_up', 'Wall Push-up', 'upper', 'push', array['chest', 'arms', 'shoulders']::text[], 1, 'reps', false, 'small', false, false, false, false, array['wall']::text[], 3.0, 'push_up', false, false, 'wall_push_up', 'The gentlest push-up. Builds the pattern with very little load.', array['Stand an arm''s length from a wall, hands at chest height, shoulder-width apart.', 'Keep your body in one straight line from head to heels.', 'Bend your elbows to bring your chest toward the wall, elbows at about 45°.', 'Press the wall away until your arms are straight.']::text[], array['Letting the hips sag forward', 'Flaring elbows straight out']::text[]),
  ('incline_push_up', 'Incline Push-up', 'upper', 'push', array['chest', 'arms', 'shoulders']::text[], 2, 'reps', false, 'small', false, false, false, true, array['elevated']::text[], 3.0, 'push_up', false, false, 'incline_push_up', 'Hands on a sturdy bed edge, sofa or chair. The higher the surface, the easier it is.', array['Place your hands on a stable raised surface, slightly wider than your shoulders.', 'Walk your feet back until your body is a straight plank.', 'Lower your chest to the edge with control.', 'Push back up, squeezing your glutes the whole time.']::text[], array['Using a chair that can slide — brace it against a wall', 'Piking the hips up']::text[]),
  ('knee_push_up', 'Knee Push-up', 'upper', 'push', array['chest', 'arms', 'shoulders']::text[], 3, 'reps', false, 'small', false, true, true, true, '{}'::text[], 3.0, 'push_up', false, false, 'knee_push_up', 'A full-range push-up with a shorter lever.', array['Kneel with a towel under your knees, hands just wider than shoulders.', 'Keep a straight line from knees to head — hips forward, not bent.', 'Lower until your chest is a fist''s height from the floor.', 'Press the floor away and fully straighten your arms.']::text[], array['Hips bent (half-kneeling)', 'Head dropping before the chest']::text[]),
  ('push_up', 'Push-up', 'upper', 'push', array['chest', 'arms', 'shoulders']::text[], 4, 'reps', false, 'small', false, true, false, true, '{}'::text[], 3.0, 'push_up', false, false, 'push_up', 'The foundation of upper-body bodyweight strength.', array['Hands under shoulders, feet together, body in a straight line.', 'Brace your abs and squeeze your glutes.', 'Lower as one unit until your chest nearly touches the floor, elbows at 45°.', 'Push the floor away until your arms are straight.']::text[], array['Sagging hips', 'Partial reps', 'Elbows flared to 90°']::text[]),
  ('diamond_push_up', 'Diamond Push-up', 'upper', 'push', array['arms', 'chest']::text[], 5, 'reps', false, 'small', false, true, false, true, '{}'::text[], 3.0, 'push_up', false, false, 'push_up', 'Hands close together to shift the work to the triceps.', array['Make a diamond with your thumbs and index fingers under your chest.', 'Keep your elbows tucked close to your ribs.', 'Lower until your chest touches your hands.', 'Press up without letting your hips lead.']::text[], array['Elbows flaring wide', 'Shortening the range']::text[]),
  ('decline_push_up', 'Decline Push-up', 'upper', 'push', array['chest', 'shoulders']::text[], 6, 'reps', false, 'small', false, true, false, true, array['elevated']::text[], 3.0, 'push_up', false, false, 'decline_push_up', 'Feet on a bed, sofa or chair to load the upper chest and shoulders.', array['Put your feet on a stable raised surface, hands on the floor under your shoulders.', 'Keep your body straight — don''t let the hips sag.', 'Lower your forehead-to-chest area toward the floor.', 'Press back up to straight arms.']::text[], array['Hips piking up to make it easier']::text[]),
  ('pike_push_up', 'Pike Push-up', 'upper', 'push', array['shoulders', 'arms']::text[], 6, 'reps', false, 'small', false, true, false, true, '{}'::text[], 3.0, null, false, false, 'pike_push_up', 'Hips high in an upside-down V to train the shoulders.', array['Start in a push-up, then walk your feet in and lift your hips high.', 'Keep your arms straight and head between your arms.', 'Bend your elbows to lower the top of your head toward the floor in front of your hands.', 'Press back up to the V shape.']::text[], array['Dropping the hips into a push-up', 'Elbows flaring out']::text[]),
  ('archer_push_up', 'Archer Push-up', 'upper', 'push', array['chest', 'arms', 'shoulders']::text[], 7, 'reps', true, 'small', false, true, false, true, '{}'::text[], 3.0, 'push_up', false, false, 'push_up', 'A wide push-up that shifts most of the load to one arm.', array['Set your hands very wide, fingers turned slightly out.', 'Lower toward one hand while the other arm straightens out to the side.', 'Keep your hips square to the floor.', 'Push back to the centre and alternate sides.']::text[], array['Twisting the hips', 'Bending the straight arm']::text[]),
  ('pseudo_planche_push_up', 'Pseudo Planche Push-up', 'upper', 'push', array['shoulders', 'chest']::text[], 8, 'reps', false, 'small', false, true, false, true, '{}'::text[], 3.0, 'push_up', false, false, 'push_up', 'Hands by the hips and shoulders leaning forward — a serious strength builder.', array['Place your hands beside your lower ribs, fingers turned out.', 'Lean your shoulders forward past your hands.', 'Lower with control while keeping the forward lean.', 'Press up and keep the shoulders protracted.']::text[], array['Losing the lean at the bottom']::text[]),
  ('incline_one_arm_push_up', 'Incline One-arm Push-up', 'upper', 'push', array['chest', 'arms', 'shoulders']::text[], 8, 'reps', true, 'small', false, false, false, true, array['elevated']::text[], 3.0, 'push_up', false, false, 'incline_push_up', 'One-arm push-up with the hand on a raised surface.', array['Place one hand on a sturdy raised surface, feet wide for balance.', 'Put your free hand behind your back.', 'Lower your chest toward the hand, keeping your hips square.', 'Press up without twisting.']::text[], array['Rotating the torso open']::text[]),
  ('one_arm_push_up', 'One-arm Push-up', 'upper', 'push', array['chest', 'arms', 'shoulders']::text[], 10, 'reps', true, 'small', false, true, false, true, '{}'::text[], 3.0, 'push_up', false, false, 'push_up', 'The top of the push-up path.', array['Feet wider than shoulders, one hand under your chest.', 'Brace hard — glutes, abs and the free-side lat.', 'Lower slowly until your chest is just above the floor.', 'Drive up without letting the hips rotate.']::text[], array['Twisting through the torso']::text[]),
  ('chair_dip', 'Chair Dip', 'upper', 'push', array['arms', 'chest']::text[], 4, 'reps', false, 'small', false, false, false, true, array['elevated']::text[], 3.0, null, false, false, 'dip', 'Triceps builder on a sturdy chair, bed edge or sofa.', array['Sit on the edge, hands beside your hips, fingers forward.', 'Slide your hips off the edge, knees bent.', 'Lower until your elbows reach about 90°, keeping them pointed back.', 'Press up to straight arms.']::text[], array['Going too deep and rolling the shoulders forward', 'Using a chair on wheels']::text[]),
  ('shoulder_tap', 'Plank Shoulder Tap', 'core', 'coreRotation', array['core', 'shoulders']::text[], 3, 'reps', true, 'small', false, true, false, true, '{}'::text[], 3.0, null, false, false, 'plank_tap', 'Anti-rotation core work in a high plank.', array['High plank with feet slightly wider than hips.', 'Lift one hand and tap the opposite shoulder.', 'Keep your hips as still as possible.', 'Alternate slowly.']::text[], array['Rocking the hips side to side']::text[]),
  ('plank_up_down', 'Plank Up-down', 'upper', 'push', array['arms', 'core']::text[], 5, 'reps', false, 'small', false, true, false, true, '{}'::text[], 3.0, null, false, false, 'plank_tap', 'Move between forearm and high plank.', array['Start in a forearm plank.', 'Press up one hand at a time into a high plank.', 'Lower back down one forearm at a time.', 'Alternate the leading arm each rep.']::text[], array['Swaying the hips']::text[]),
  ('towel_curl_hold', 'Towel Curl Hold', 'upper', 'pull', array['arms']::text[], 2, 'seconds', false, 'small', false, false, false, false, array['towel']::text[], 3.0, null, false, false, 'towel_row', 'Isometric biceps work: pull up on a towel trapped under your foot.', array['Stand on the middle of a towel, holding both ends.', 'Bend your elbows to 90°.', 'Pull upward as hard as you can without moving — the towel won''t let you.', 'Breathe steadily and hold.']::text[], array['Holding your breath', 'Leaning back']::text[]),
  ('wall_handstand_hold', 'Wall Handstand Hold', 'upper', 'push', array['shoulders']::text[], 8, 'seconds', false, 'small', false, true, false, true, array['wall']::text[], 3.0, null, false, false, 'pike_push_up', 'Chest-to-wall handstand for shoulder strength.', array['Face away from the wall in a push-up position, feet against the wall.', 'Walk your feet up and hands in until your body is steep and straight.', 'Push tall through your shoulders.', 'Walk down with control before you tire.']::text[], array['Arching the lower back', 'Staying up until failure']::text[]),
  ('prone_y_raise', 'Prone Y Raise', 'upper', 'pull', array['back', 'shoulders']::text[], 1, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'prone_raise', 'Wakes up the upper back and rear shoulders.', array['Lie face down, arms overhead in a Y, thumbs up.', 'Squeeze your shoulder blades down and back.', 'Lift your arms a few centimetres off the floor.', 'Pause for a second, then lower.']::text[], array['Shrugging toward the ears']::text[]),
  ('prone_ytw', 'Prone Y-T-W', 'upper', 'pull', array['back', 'shoulders']::text[], 2, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'prone_raise', 'Three arm positions to strengthen the whole upper back.', array['Lie face down with your forehead on a towel.', 'Raise your arms in a Y, lower; then a T, lower; then a W, lower.', 'Lead with your shoulder blades, not your hands.', 'That''s one rep.']::text[], array['Lifting the chest high instead of the arms']::text[]),
  ('superman_hold', 'Superman Hold', 'upper', 'hinge', array['back', 'core']::text[], 3, 'seconds', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'superman', 'Holds the whole back line strong.', array['Lie face down, arms overhead.', 'Lift arms, chest and legs off the floor together.', 'Keep your neck long — look at the floor.', 'Hold and breathe.']::text[], array['Cranking the neck up']::text[]),
  ('towel_row_hold', 'Towel Row Hold', 'upper', 'pull', array['back', 'shoulders']::text[], 3, 'seconds', false, 'small', false, false, false, false, array['towel']::text[], 3.0, null, false, false, 'towel_row', 'Isometric row: pull a towel apart around your feet.', array['Sit tall with legs straight and a towel looped around your feet.', 'Pull the ends toward your ribs, elbows back.', 'Squeeze your shoulder blades together as hard as you can.', 'Hold without leaning back.']::text[], array['Rounding the upper back']::text[]),
  ('reverse_snow_angel', 'Reverse Snow Angel', 'upper', 'pull', array['back', 'shoulders']::text[], 4, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'prone_raise', 'A big sweeping arc that builds the upper back.', array['Lie face down, arms by your sides, palms down, hands slightly lifted.', 'Sweep your arms in a wide arc overhead without touching the floor.', 'Sweep back to your hips.', 'Keep your chest down and move slowly.']::text[], array['Letting the hands touch down to rest']::text[]),
  ('prone_swimmer', 'Prone Swimmer', 'upper', 'pull', array['back', 'shoulders']::text[], 5, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'prone_raise', 'Continuous upper-back endurance.', array['Lie face down with chest and arms slightly lifted.', 'Pull your elbows down to your ribs like a pull-up.', 'Reach back overhead.', 'Keep everything off the floor for the whole set.']::text[], array['Dropping the chest between reps']::text[]),
  ('towel_floor_pull', 'Towel Floor Pull', 'upper', 'pull', array['back', 'shoulders']::text[], 6, 'reps', false, 'medium', false, true, false, false, array['towel']::text[], 3.0, null, false, false, 'floor_pull', 'Lie on a towel on a smooth floor and pull yourself forward with your forearms.', array['Lie face down on a towel on a smooth floor (tile or wood).', 'Reach forward and plant your forearms.', 'Pull your body forward by driving your elbows down and back.', 'Reset and repeat.']::text[], array['Pushing with the feet']::text[]),
  ('arch_body_hold', 'Arch Body Hold', 'upper', 'hinge', array['back', 'core']::text[], 7, 'seconds', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'superman', 'The mirror of the hollow hold — a strong, tight banana shape face down.', array['Lie face down, arms overhead, legs together.', 'Lift arms, chest and legs into a smooth arch.', 'Squeeze glutes and reach long.', 'Hold without bending the knees.']::text[], array['Bending the knees to lift higher']::text[]),
  ('arch_body_rock', 'Arch Body Rock', 'upper', 'hinge', array['back', 'core']::text[], 8, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'superman', 'Rock in a locked arch hold.', array['Get into a tight arch hold.', 'Rock forward and back as one unit.', 'Never let the shape collapse.', 'Keep your breathing steady.']::text[], array['Breaking the shape']::text[]),
  ('wall_angel', 'Wall Angel', 'upper', 'pull', array['back', 'shoulders']::text[], 1, 'reps', false, 'small', false, false, false, false, array['wall']::text[], 3.0, null, true, true, 'wall_angel', 'Posture and shoulder mobility against a wall.', array['Stand with your back, head and hips against a wall.', 'Raise your arms in a W, backs of hands on the wall.', 'Slide them up to a Y and back down.', 'Keep your ribs down.']::text[], array['Arching the lower back off the wall']::text[]),
  ('towel_pull_apart', 'Towel Pull-apart', 'upper', 'pull', array['back', 'shoulders']::text[], 2, 'seconds', false, 'small', false, false, false, false, array['towel']::text[], 3.0, null, false, false, 'towel_row', 'Standing isometric for the upper back.', array['Hold a towel at shoulder height, arms straight.', 'Try to pull the towel apart.', 'Squeeze your shoulder blades together.', 'Hold and breathe.']::text[], array['Shrugging']::text[]),
  ('bent_over_ytw', 'Bent-over Y-T-W', 'upper', 'pull', array['back', 'shoulders']::text[], 3, 'reps', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'good_morning', 'Upper-back raises from a standing hip hinge — no floor needed.', array['Hinge at the hips with a flat back, knees soft.', 'Raise your arms in a Y, then T, then W.', 'Squeeze your shoulder blades each time.', 'Keep your back flat throughout.']::text[], array['Rounding the back']::text[]),
  ('sit_to_stand', 'Sit-to-Stand', 'legs', 'squat', array['legs']::text[], 1, 'reps', false, 'small', false, false, false, false, array['elevated']::text[], 3.0, 'squat', false, false, 'sit_to_stand', 'Squat to a chair or bed — the safest way to learn the squat.', array['Stand in front of a sturdy chair or bed, feet shoulder-width.', 'Push your hips back and sit down with control.', 'Lightly touch the seat — don''t collapse onto it.', 'Drive through your whole foot to stand tall.']::text[], array['Knees caving in', 'Rocking forward to stand']::text[]),
  ('quarter_squat', 'Quarter Squat', 'legs', 'squat', array['legs']::text[], 1, 'reps', false, 'small', false, false, false, false, '{}'::text[], 3.0, 'squat', false, false, 'squat', 'A shallow squat for limited mobility days.', array['Feet shoulder-width, arms forward for balance.', 'Bend knees and hips a quarter of the way down.', 'Keep your heels planted and chest up.', 'Stand tall and squeeze your glutes.']::text[], array['Knees drifting inward']::text[]),
  ('bodyweight_squat', 'Squat', 'legs', 'squat', array['legs']::text[], 2, 'reps', false, 'small', false, false, false, false, '{}'::text[], 3.0, 'squat', false, false, 'squat', 'The fundamental lower-body movement.', array['Feet shoulder-width, toes turned out slightly.', 'Sit your hips back and down, knees tracking over your toes.', 'Go as low as you can with heels down and a proud chest.', 'Drive up through your whole foot.']::text[], array['Heels lifting', 'Knees caving in']::text[]),
  ('pause_squat', 'Pause Squat', 'legs', 'squat', array['legs']::text[], 3, 'reps', false, 'small', false, false, false, false, '{}'::text[], 5.0, 'squat', false, false, 'squat', 'Squat with a 2-second pause at the bottom.', array['Squat down with control.', 'Hold the bottom position for two full seconds, staying tight.', 'Drive up hard.', 'Reset your breath at the top.']::text[], array['Relaxing at the bottom']::text[]),
  ('split_squat', 'Split Squat', 'legs', 'lunge', array['legs']::text[], 4, 'reps', true, 'small', false, false, true, false, '{}'::text[], 3.0, 'squat', false, false, 'split_squat', 'A staggered-stance squat that builds single-leg strength.', array['Take a long step, back heel lifted.', 'Lower straight down until your back knee almost touches the floor.', 'Keep your torso upright and front heel planted.', 'Push through the front foot to rise. Finish one side, then switch.']::text[], array['Stance too short', 'Front knee collapsing inward']::text[]),
  ('tempo_split_squat', 'Tempo Split Squat', 'legs', 'lunge', array['legs']::text[], 5, 'reps', true, 'small', false, false, true, false, '{}'::text[], 5.0, 'squat', false, false, 'split_squat', 'Three seconds down, one second up — no furniture needed.', array['Split stance, back heel up.', 'Lower for a slow count of three.', 'Pause just above the floor.', 'Drive up in one second.']::text[], array['Rushing the lowering']::text[]),
  ('bulgarian_split_squat', 'Bulgarian Split Squat', 'legs', 'lunge', array['legs']::text[], 6, 'reps', true, 'small', false, false, true, false, array['elevated']::text[], 3.0, 'squat', false, false, 'bulgarian', 'Rear foot on a bed, sofa or chair. A brutal single-leg builder.', array['Stand a big step in front of a bed, sofa or chair and rest your rear foot on it.', 'Lower until your front thigh is about parallel to the floor.', 'Keep your weight in the front heel.', 'Drive back up. Finish one side, then switch.']::text[], array['Front foot too close to the support', 'Pushing off the back foot']::text[]),
  ('skater_squat', 'Skater Squat', 'legs', 'squat', array['legs']::text[], 7, 'reps', true, 'small', false, false, true, false, '{}'::text[], 3.0, 'squat', false, false, 'pistol', 'Single-leg squat with the back knee lowering to a towel.', array['Stand on one leg, the other bent behind you.', 'Reach your arms forward and lower until the back knee touches a folded towel.', 'Keep the standing heel down.', 'Stand up without pushing off the back leg.']::text[], array['Dropping hard onto the knee']::text[]),
  ('assisted_pistol_squat', 'Assisted Pistol Squat', 'legs', 'squat', array['legs']::text[], 8, 'reps', true, 'small', false, false, true, false, array['wall']::text[], 3.0, 'squat', false, false, 'pistol', 'Pistol squat with a hand on the wall or door frame for balance.', array['Stand side-on to a wall, one hand lightly on it.', 'Lift one leg forward and squat down on the other.', 'Use the wall only for balance, not to pull.', 'Stand up tall.']::text[], array['Pulling on the wall']::text[]),
  ('box_pistol_squat', 'Pistol to Box', 'legs', 'squat', array['legs']::text[], 9, 'reps', true, 'small', false, false, true, false, array['elevated']::text[], 3.0, 'squat', false, false, 'pistol', 'Single-leg squat down to a chair or bed edge.', array['Stand in front of a chair or bed on one leg.', 'Reach forward and slowly sit to the edge.', 'Touch lightly, don''t rest.', 'Stand up on one leg.']::text[], array['Crashing onto the seat']::text[]),
  ('pistol_squat', 'Pistol Squat', 'legs', 'squat', array['legs']::text[], 10, 'reps', true, 'small', false, false, true, false, '{}'::text[], 3.0, 'squat', false, false, 'pistol', 'The top of the leg path.', array['Stand on one leg, arms forward, other leg straight out.', 'Squat all the way down with control.', 'Keep the standing heel down.', 'Drive up without letting the knee cave.']::text[], array['Losing the heel', 'Bouncing out of the bottom']::text[]),
  ('reverse_lunge', 'Reverse Lunge', 'legs', 'lunge', array['legs']::text[], 3, 'reps', true, 'small', false, false, true, false, '{}'::text[], 3.0, null, false, false, 'lunge', 'Step back into a lunge — kinder on the knees than forward lunges.', array['Stand tall, feet hip-width.', 'Step one foot back and lower until both knees bend to about 90°.', 'Keep your front heel planted.', 'Push through the front foot to return. Alternate legs.']::text[], array['Leaning far forward']::text[]),
  ('lateral_lunge', 'Lateral Lunge', 'legs', 'lunge', array['legs']::text[], 4, 'reps', true, 'medium', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'lateral_lunge', 'Side-to-side strength for hips and inner thighs.', array['Take a wide step to the side.', 'Sit back into that hip, keeping the other leg straight.', 'Keep both feet flat and chest up.', 'Push back to the centre.']::text[], array['Bent knee caving forward']::text[]),
  ('curtsy_lunge', 'Curtsy Lunge', 'legs', 'lunge', array['legs']::text[], 4, 'reps', true, 'small', false, false, true, false, '{}'::text[], 3.0, null, false, false, 'lunge', 'Cross-behind lunge for the glutes.', array['Step one leg diagonally behind the other.', 'Lower until the front thigh is near parallel.', 'Keep your hips facing forward.', 'Return and alternate.']::text[], array['Twisting the hips']::text[]),
  ('step_up', 'Step-up', 'legs', 'lunge', array['legs']::text[], 4, 'reps', true, 'small', false, false, false, false, array['elevated']::text[], 3.0, null, false, false, 'step_up', 'Step onto a sturdy, low surface. Use a bottom stair or a stable low box, never a wheeled chair.', array['Place one whole foot on a low, stable step.', 'Drive through that heel to stand up tall.', 'Lower slowly with control.', 'Finish one side, then switch.']::text[], array['Pushing off the bottom foot']::text[]),
  ('wall_sit', 'Wall Sit', 'legs', 'squat', array['legs']::text[], 3, 'seconds', false, 'small', false, false, false, false, array['wall']::text[], 3.0, null, false, false, 'wall_sit', 'A burning isometric hold for the thighs.', array['Lean your back against a wall.', 'Slide down until your knees are about 90°.', 'Keep your weight in your heels.', 'Hold and breathe.']::text[], array['Hands pushing on the thighs']::text[]),
  ('calf_raise', 'Calf Raise', 'legs', 'squat', array['legs']::text[], 1, 'reps', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'calf_raise', 'Strong ankles and calves.', array['Stand tall near a wall for balance.', 'Rise onto the balls of your feet as high as you can.', 'Pause at the top.', 'Lower slowly.']::text[], array['Bouncing']::text[]),
  ('single_leg_calf_raise', 'Single-leg Calf Raise', 'legs', 'squat', array['legs']::text[], 3, 'reps', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'calf_raise', 'Calf raise on one leg.', array['Stand on one foot, fingertips on a wall.', 'Rise as high as possible.', 'Pause for a second.', 'Lower all the way down.']::text[], array['Rushing the lowering']::text[]),
  ('walking_lunge', 'Walking Lunge', 'legs', 'lunge', array['legs']::text[], 4, 'reps', false, 'large', false, false, true, false, '{}'::text[], 3.0, null, false, false, 'lunge', 'Travelling lunges — needs room to walk.', array['Step forward into a lunge.', 'Lower the back knee toward the floor.', 'Drive up and step straight into the next lunge.', 'Keep your torso tall.']::text[], array['Short steps']::text[]),
  ('cossack_squat', 'Cossack Squat', 'legs', 'lunge', array['legs']::text[], 6, 'reps', true, 'medium', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'lateral_lunge', 'A deep side squat that builds strength and mobility.', array['Take a very wide stance.', 'Squat deep to one side, the other leg straight with toes up.', 'Keep the working heel down.', 'Shift across to the other side.']::text[], array['Heel lifting']::text[]),
  ('glute_bridge', 'Glute Bridge', 'legs', 'hinge', array['legs', 'core']::text[], 1, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'glute_bridge', 'Wakes up the glutes and protects the lower back.', array['Lie on your back, knees bent, feet flat and hip-width.', 'Press through your heels and lift your hips.', 'Squeeze your glutes hard at the top — ribs down.', 'Lower slowly.']::text[], array['Arching the lower back instead of using the glutes']::text[]),
  ('glute_bridge_march', 'Bridge March', 'legs', 'hinge', array['legs', 'core']::text[], 2, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'glute_bridge', 'Hold a bridge and march one knee up at a time.', array['Lift into a glute bridge.', 'Lift one foot a few centimetres without the hips dropping.', 'Put it down and switch.', 'Keep the hips level.']::text[], array['Hips tilting']::text[]),
  ('b_stance_glute_bridge', 'B-stance Bridge', 'legs', 'hinge', array['legs']::text[], 3, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'glute_bridge', 'One foot slightly forward so the other leg does most of the work.', array['Set one foot a half-step forward on its heel.', 'Drive through the back foot to bridge up.', 'Squeeze at the top.', 'Finish one side, then switch.']::text[], array['Pushing through the front foot']::text[]),
  ('single_leg_glute_bridge', 'Single-leg Glute Bridge', 'legs', 'hinge', array['legs']::text[], 4, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'glute_bridge', 'Bridge on one leg.', array['One foot flat, the other leg straight or knee hugged.', 'Drive through the planted heel.', 'Keep your hips level at the top.', 'Lower slowly.']::text[], array['Hips rotating']::text[]),
  ('hip_thrust', 'Hip Thrust', 'legs', 'hinge', array['legs']::text[], 5, 'reps', false, 'small', false, true, false, false, array['elevated']::text[], 3.0, null, false, false, 'hip_thrust', 'Upper back on a sofa or bed edge for a bigger range than a bridge.', array['Sit with your shoulder blades against a sofa or bed edge.', 'Feet flat, knees bent.', 'Drive your hips up until your torso is flat like a table.', 'Chin tucked, squeeze, then lower.']::text[], array['Over-arching at the top']::text[]),
  ('single_leg_rdl', 'Single-leg Hip Hinge', 'legs', 'hinge', array['legs']::text[], 5, 'reps', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'single_leg_rdl', 'Balance and hamstring strength on one leg.', array['Stand on one leg, knee soft.', 'Hinge forward as your free leg reaches back, body like a seesaw.', 'Keep your hips square to the floor.', 'Squeeze the glute to stand tall.']::text[], array['Opening the hip toward the ceiling']::text[]),
  ('single_leg_hip_thrust', 'Single-leg Hip Thrust', 'legs', 'hinge', array['legs']::text[], 6, 'reps', true, 'small', false, true, false, false, array['elevated']::text[], 3.0, null, false, false, 'hip_thrust', 'Hip thrust on one leg.', array['Upper back on the sofa or bed edge.', 'One foot planted, the other knee pulled in.', 'Drive the hips up level.', 'Lower with control.']::text[], array['Hips twisting']::text[]),
  ('hamstring_walkout', 'Hamstring Walkout', 'legs', 'hinge', array['legs']::text[], 7, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'glute_bridge', 'Walk your heels out from a bridge — hard on the hamstrings.', array['Lift into a glute bridge.', 'Take small heel steps away from you while keeping the hips up.', 'Go as far as you can control.', 'Walk them back in.']::text[], array['Hips dropping as the feet walk out']::text[]),
  ('towel_leg_curl', 'Towel Leg Curl', 'legs', 'hinge', array['legs']::text[], 8, 'reps', false, 'small', false, true, false, false, array['towel']::text[], 3.0, null, false, false, 'leg_curl', 'Heels on a towel on a smooth floor — slide in and out from a bridge.', array['Lie on your back, heels on a towel on a smooth floor.', 'Lift your hips into a bridge.', 'Slide your heels out until your legs are nearly straight.', 'Curl them back in while keeping the hips high.']::text[], array['Letting the hips drop']::text[]),
  ('single_leg_towel_curl', 'Single-leg Towel Curl', 'legs', 'hinge', array['legs']::text[], 9, 'reps', true, 'small', false, true, false, false, array['towel']::text[], 3.0, null, false, false, 'leg_curl', 'The top of the hip path.', array['One heel on the towel, the other leg lifted.', 'Bridge up and slide the heel out.', 'Curl back in with the hips high.', 'Finish one side, then switch.']::text[], array['Rushing']::text[]),
  ('standing_glute_kickback', 'Standing Glute Kickback', 'legs', 'hinge', array['legs']::text[], 1, 'reps', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, true, 'kickback', 'Glute activation without getting on the floor.', array['Stand tall, hands on a wall.', 'Kick one leg straight back, squeezing the glute.', 'Don''t arch your lower back.', 'Return and repeat.']::text[], array['Swinging the leg']::text[]),
  ('good_morning', 'Bodyweight Good Morning', 'legs', 'hinge', array['legs']::text[], 2, 'reps', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, true, 'good_morning', 'Learn the hip hinge.', array['Hands behind your head, feet hip-width, knees soft.', 'Push your hips back as your chest tips forward.', 'Keep a flat back and feel the hamstrings stretch.', 'Squeeze your glutes to stand.']::text[], array['Rounding the back']::text[]),
  ('dead_bug', 'Dead Bug', 'core', 'coreAnterior', array['core']::text[], 1, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'dead_bug', 'Teaches your abs to keep your back flat while your limbs move.', array['Lie on your back, arms up, knees bent at 90° over your hips.', 'Press your lower back into the floor.', 'Slowly reach one arm back and the opposite leg out.', 'Return and switch sides.']::text[], array['Lower back lifting off the floor']::text[]),
  ('wall_plank', 'Wall Plank', 'core', 'coreAnterior', array['core']::text[], 1, 'seconds', false, 'small', false, false, false, false, array['wall']::text[], 3.0, 'plank', false, false, 'wall_push_up', 'A standing plank on a wall.', array['Forearms on the wall, walk your feet back.', 'Make a straight line from head to heels.', 'Brace your abs as if bracing for a poke.', 'Hold and breathe.']::text[], array['Hips sagging toward the wall']::text[]),
  ('plank', 'Plank', 'core', 'coreAnterior', array['core']::text[], 2, 'seconds', false, 'small', false, true, false, false, '{}'::text[], 3.0, 'plank', false, false, 'plank', 'The classic core hold.', array['Forearms under shoulders, legs straight behind you.', 'Squeeze glutes and pull your belly button in.', 'Keep a straight line — no sagging, no piking.', 'Breathe slowly and hold.']::text[], array['Hips sagging', 'Holding your breath']::text[]),
  ('long_lever_plank', 'Long Plank', 'core', 'coreAnterior', array['core']::text[], 4, 'seconds', false, 'small', false, true, false, false, '{}'::text[], 3.0, 'plank', false, false, 'plank', 'Elbows further forward than your shoulders — much harder on the abs.', array['Start in a forearm plank.', 'Walk your elbows forward a few centimetres past your head.', 'Keep your hips level and ribs tucked.', 'Hold.']::text[], array['Lower back arching']::text[]),
  ('side_plank', 'Side Plank', 'core', 'coreLateral', array['core']::text[], 4, 'seconds', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'side_plank', 'Builds the obliques and a stable waist.', array['Lie on your side, elbow under your shoulder.', 'Stack your feet and lift your hips.', 'Make a straight line from head to feet.', 'Hold, then switch sides.']::text[], array['Hips dropping backward']::text[]),
  ('hollow_body_hold', 'Hollow Body Hold', 'core', 'coreAnterior', array['core']::text[], 6, 'seconds', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'hollow_hold', 'The gymnast''s core foundation.', array['Lie on your back and press your lower back into the floor.', 'Lift your shoulders and legs a few centimetres.', 'Reach your arms overhead (bend the knees to make it easier).', 'Hold without the lower back lifting.']::text[], array['Lower back peeling off the floor']::text[]),
  ('hollow_body_rock', 'Hollow Rock', 'core', 'coreAnterior', array['core']::text[], 7, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'hollow_rock', 'Rock back and forth in a hollow hold.', array['Get into a hollow hold.', 'Rock from your upper back to your hips as one unit.', 'Keep the shape locked.', 'Stop the set if the shape breaks.']::text[], array['Bending at the hips']::text[]),
  ('v_up', 'V-up', 'core', 'coreAnterior', array['core']::text[], 8, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'v_up', 'Explosive full-range abs.', array['Lie flat, arms overhead.', 'Lift your legs and chest together to touch your toes.', 'Lower slowly back to a hollow position.', 'Don''t fully relax between reps.']::text[], array['Using momentum to crash down']::text[]),
  ('tuck_l_sit', 'Tuck L-sit', 'core', 'coreAnterior', array['core', 'arms']::text[], 9, 'seconds', false, 'small', false, true, false, true, '{}'::text[], 3.0, null, false, false, 'l_sit', 'Hands on the floor, lift your whole body with knees tucked.', array['Sit with hands flat beside your hips.', 'Press down hard and lift your hips off the floor.', 'Pull your knees to your chest.', 'Hold.']::text[], array['Shrugging shoulders to the ears']::text[]),
  ('bicycle_crunch', 'Bicycle Crunch', 'core', 'coreRotation', array['core']::text[], 3, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'crunch', 'Rotation for the obliques.', array['Lie on your back, hands lightly behind your head.', 'Bring one elbow toward the opposite knee while the other leg extends.', 'Rotate from your ribs, not your neck.', 'Alternate slowly.']::text[], array['Pulling on the neck']::text[]),
  ('reverse_crunch', 'Reverse Crunch', 'core', 'coreAnterior', array['core']::text[], 3, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'leg_raise', 'Lower-ab focus by curling the hips up.', array['Lie on your back, knees bent at 90° in the air.', 'Curl your hips off the floor toward your chest.', 'Lower slowly.', 'Keep it controlled, no swinging.']::text[], array['Swinging the legs']::text[]),
  ('leg_raise', 'Lying Leg Raise', 'core', 'coreAnterior', array['core']::text[], 5, 'reps', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'leg_raise', 'Straight-leg raises for the lower abs.', array['Lie flat, hands under your hips if needed.', 'Keep your lower back pressed down.', 'Raise your straight legs to vertical.', 'Lower slowly, stopping before your back arches.']::text[], array['Back arching as the legs lower']::text[]),
  ('flutter_kicks', 'Flutter Kicks', 'core', 'coreAnterior', array['core']::text[], 4, 'seconds', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'leg_raise', 'Small fast kicks with the lower back glued down.', array['Lie on your back, legs straight and slightly lifted.', 'Kick small and quick.', 'Keep your lower back down.', 'Breathe steadily.']::text[], array['Legs too high to be useful']::text[]),
  ('bird_dog', 'Bird Dog', 'core', 'coreRotation', array['core', 'back']::text[], 2, 'reps', true, 'small', false, true, true, false, '{}'::text[], 3.0, null, false, false, 'bird_dog', 'Spine-friendly core stability.', array['On hands and knees, back flat.', 'Reach one arm forward and the opposite leg back.', 'Pause without rocking.', 'Return and switch.']::text[], array['Arching the back']::text[]),
  ('side_plank_hip_dip', 'Side Plank Hip Dip', 'core', 'coreLateral', array['core']::text[], 5, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'side_plank', 'Dynamic side plank.', array['Get into a side plank.', 'Lower your hip toward the floor.', 'Lift it back up higher than a straight line.', 'Finish one side, then switch.']::text[], array['Rolling forward']::text[]),
  ('russian_twist', 'Russian Twist', 'core', 'coreRotation', array['core']::text[], 3, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'crunch', 'Rotational core with feet down or up.', array['Sit leaning back slightly, chest up.', 'Rotate your shoulders to one side, then the other.', 'Move from your ribs, not just your arms.', 'Lift your feet to make it harder.']::text[], array['Rounding the back']::text[]),
  ('standing_knee_to_elbow', 'Standing Knee-to-Elbow', 'core', 'coreRotation', array['core']::text[], 1, 'reps', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, true, 'march', 'Standing core work — no floor needed.', array['Stand tall, hands behind your head.', 'Lift one knee as you crunch the opposite elbow toward it.', 'Stand tall again.', 'Alternate sides.']::text[], array['Hunching the back instead of crunching']::text[]),
  ('heel_taps', 'Heel Taps', 'core', 'coreLateral', array['core']::text[], 2, 'reps', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, false, false, 'crunch', 'Side-to-side oblique crunch.', array['Lie on your back, knees bent, shoulders slightly lifted.', 'Reach one hand to touch that heel.', 'Switch sides.', 'Keep the shoulders off the floor.']::text[], array['Dropping the head between reps']::text[]),
  ('standing_side_crunch', 'Standing Side Crunch', 'core', 'coreLateral', array['core']::text[], 1, 'reps', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'march', 'Lift a knee to the side while crunching the elbow down to it.', array['Stand tall, hands behind your head.', 'Lift one knee out to the side as the same-side elbow comes down.', 'Squeeze the side of your waist.', 'Return and repeat.']::text[], array['Leaning forward']::text[]),
  ('march_in_place', 'March in Place', 'conditioning', 'conditioning', array['fullBody']::text[], 1, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, true, 'march', 'Low-impact warm-up and conditioning.', array['Stand tall.', 'Drive your knees up to hip height.', 'Swing your arms.', 'Keep a steady rhythm.']::text[], array['Slouching']::text[]),
  ('step_jack', 'Step Jack', 'conditioning', 'conditioning', array['fullBody']::text[], 2, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, true, 'jack', 'A jumping jack without the jump — quiet and joint-friendly.', array['Step one foot out as your arms rise overhead.', 'Step back in as your arms lower.', 'Alternate sides.', 'Speed up as you warm up.']::text[], array['Half-raising the arms']::text[]),
  ('shadow_boxing', 'Shadow Boxing', 'conditioning', 'conditioning', array['fullBody']::text[], 3, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'shadow_box', 'Low-impact cardio that works shoulders and core.', array['Stand staggered, fists up by your chin.', 'Throw fast straight punches, rotating through your hips.', 'Stay light on your feet.', 'Breathe out with each punch.']::text[], array['Locking the elbows hard']::text[]),
  ('low_impact_skater', 'Low-impact Skater', 'conditioning', 'conditioning', array['fullBody']::text[], 3, 'seconds', false, 'medium', false, false, false, false, '{}'::text[], 3.0, null, false, false, 'skater', 'Side-to-side steps with a curtsy reach.', array['Step wide to one side.', 'Sweep the trailing leg behind you.', 'Reach toward the front foot.', 'Switch sides with rhythm.']::text[], array['Knee caving']::text[]),
  ('speed_squat', 'Speed Squat', 'conditioning', 'conditioning', array['legs', 'fullBody']::text[], 4, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, 'squat', false, false, 'squat', 'Fast, controlled squats for conditioning.', array['Squat to a comfortable depth.', 'Stand up fast.', 'Keep your form clean.', 'Keep moving.']::text[], array['Sloppy depth']::text[]),
  ('mountain_climber', 'Mountain Climber', 'conditioning', 'conditioning', array['core', 'fullBody']::text[], 4, 'seconds', false, 'small', false, true, false, true, '{}'::text[], 3.0, null, false, false, 'mountain_climber', 'Run in a plank.', array['High plank, hands under shoulders.', 'Drive one knee toward your chest, then switch fast.', 'Keep your hips low.', 'Stay on the balls of your feet.']::text[], array['Hips bouncing high']::text[]),
  ('jumping_jack', 'Jumping Jack', 'conditioning', 'conditioning', array['fullBody']::text[], 4, 'seconds', false, 'small', true, false, false, false, '{}'::text[], 3.0, null, false, false, 'jack', 'Classic cardio.', array['Jump your feet out as your arms rise.', 'Jump back in as they lower.', 'Land softly.', 'Keep a rhythm.']::text[], array['Landing heavily']::text[]),
  ('high_knees', 'High Knees', 'conditioning', 'conditioning', array['fullBody']::text[], 5, 'seconds', false, 'small', true, false, false, false, '{}'::text[], 3.0, null, false, false, 'march', 'Sprint on the spot.', array['Run in place, knees up to hip height.', 'Pump your arms.', 'Stay on the balls of your feet.', 'Go fast.']::text[], array['Leaning back']::text[]),
  ('inchworm', 'Inchworm', 'conditioning', 'conditioning', array['fullBody', 'shoulders']::text[], 4, 'reps', false, 'medium', false, true, false, true, '{}'::text[], 3.0, null, false, true, 'burpee', 'Walk your hands out to a plank and back.', array['Stand tall, then hinge and place your hands on the floor.', 'Walk your hands out to a high plank.', 'Walk them back to your feet.', 'Stand up.']::text[], array['Hips sagging in the plank']::text[]),
  ('step_back_burpee', 'Step-back Burpee', 'conditioning', 'conditioning', array['fullBody']::text[], 5, 'reps', false, 'small', false, true, false, true, '{}'::text[], 3.0, null, false, false, 'burpee', 'A burpee without jumping.', array['Squat and place your hands on the floor.', 'Step your feet back one at a time into a plank.', 'Step them back in.', 'Stand up and reach overhead.']::text[], array['Sagging plank']::text[]),
  ('squat_jump', 'Squat Jump', 'conditioning', 'conditioning', array['legs', 'fullBody']::text[], 6, 'reps', false, 'small', true, false, true, false, '{}'::text[], 3.0, null, false, false, 'squat_jump', 'Explosive jumps for power and conditioning.', array['Squat down.', 'Jump as high as you can.', 'Land softly back into the squat.', 'Reset and repeat.']::text[], array['Stiff-legged landings']::text[]),
  ('burpee_no_push_up', 'Burpee (no push-up)', 'conditioning', 'conditioning', array['fullBody']::text[], 6, 'reps', false, 'small', true, true, false, true, '{}'::text[], 3.0, null, false, false, 'burpee', 'Squat, jump back to plank, jump in, jump up.', array['Squat and put your hands down.', 'Jump your feet back to a plank.', 'Jump them back in.', 'Jump up with arms overhead.']::text[], array['Hips sagging when landing in the plank']::text[]),
  ('jumping_lunge', 'Jumping Lunge', 'conditioning', 'conditioning', array['legs']::text[], 7, 'reps', false, 'small', true, false, true, false, '{}'::text[], 3.0, null, false, false, 'lunge', 'Switch lunges in the air.', array['Start in a lunge.', 'Jump and switch legs mid-air.', 'Land softly in a lunge.', 'Keep your torso tall.']::text[], array['Knee slamming the floor']::text[]),
  ('burpee', 'Burpee', 'conditioning', 'conditioning', array['fullBody']::text[], 7, 'reps', false, 'small', true, true, false, true, '{}'::text[], 3.0, null, false, false, 'burpee', 'The full burpee with a push-up.', array['Squat and put your hands down.', 'Jump back to a plank and do a push-up.', 'Jump your feet in.', 'Jump up with arms overhead.']::text[], array['Skipping the push-up range']::text[]),
  ('burpee_tuck_jump', 'Burpee Tuck Jump', 'conditioning', 'conditioning', array['fullBody']::text[], 9, 'reps', false, 'small', true, true, true, true, '{}'::text[], 3.0, null, false, false, 'burpee', 'The top of the conditioning path.', array['Do a full burpee.', 'At the top, jump and pull your knees to your chest.', 'Land softly.', 'Go straight into the next rep.']::text[], array['Hard landings']::text[]),
  ('bear_crawl', 'Bear Crawl', 'conditioning', 'conditioning', array['fullBody', 'shoulders']::text[], 5, 'seconds', false, 'medium', false, true, true, true, '{}'::text[], 3.0, null, false, false, 'bear_crawl', 'Crawl with knees just off the floor.', array['Hands under shoulders, knees under hips, knees hovering.', 'Move opposite hand and foot together.', 'Keep your back flat like a table.', 'Go forward and back.']::text[], array['Hips high']::text[]),
  ('skater_hop', 'Skater Hop', 'conditioning', 'conditioning', array['legs', 'fullBody']::text[], 6, 'seconds', false, 'medium', true, false, false, false, '{}'::text[], 3.0, null, false, false, 'skater', 'Leap side to side like a speed skater.', array['Leap sideways onto one foot.', 'Swing the other leg behind.', 'Land softly and stick it.', 'Leap back.']::text[], array['Landing with a straight knee']::text[]),
  ('shuttle_run', 'Shuttle Run', 'conditioning', 'conditioning', array['fullBody']::text[], 6, 'seconds', false, 'large', true, false, false, false, '{}'::text[], 3.0, null, false, false, 'march', 'Sprint between two points 5–10 m apart. Needs a big space or outdoors.', array['Mark two points 5–10 metres apart.', 'Sprint to one, touch the ground.', 'Turn and sprint back.', 'Keep going for the set time.']::text[], array['Wide, slow turns']::text[]),
  ('plank_jack', 'Plank Jack', 'conditioning', 'conditioning', array['core', 'fullBody']::text[], 5, 'seconds', false, 'small', true, true, false, true, '{}'::text[], 3.0, null, false, false, 'mountain_climber', 'Jumping jacks in a plank.', array['High plank.', 'Jump your feet wide and back in.', 'Keep your hips level.', 'Stay tight.']::text[], array['Hips bouncing']::text[]),
  ('arm_circles', 'Arm Circles', 'upper', 'mobility', array['shoulders']::text[], 1, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, true, 'arm_circles', 'Warm up the shoulders.', array['Arms out to the sides.', 'Make small circles, getting bigger.', 'Reverse direction halfway.', 'Stay relaxed.']::text[], '{}'::text[]),
  ('leg_swings', 'Leg Swings', 'legs', 'mobility', array['legs']::text[], 1, 'seconds', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, true, 'leg_swing', 'Loosen the hips.', array['Hold a wall for balance.', 'Swing one leg forward and back.', 'Gradually increase the range.', 'Switch legs.']::text[], '{}'::text[]),
  ('hip_circles', 'Hip Circles', 'legs', 'mobility', array['legs']::text[], 1, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, true, 'hip_circles', 'Warm up the hips and lower back.', array['Hands on hips, feet wide.', 'Draw big slow circles with your hips.', 'Switch direction halfway.', 'Keep your knees soft.']::text[], '{}'::text[]),
  ('cat_cow', 'Cat-Cow', 'core', 'mobility', array['back', 'core']::text[], 1, 'seconds', false, 'small', false, true, true, false, '{}'::text[], 3.0, null, true, true, 'cat_cow', 'Gentle spine mobility.', array['On hands and knees.', 'Breathe in, drop your belly and lift your chest.', 'Breathe out, round your back toward the ceiling.', 'Move slowly with your breath.']::text[], '{}'::text[]),
  ('worlds_greatest_stretch', 'World''s Greatest Stretch', 'legs', 'mobility', array['fullBody']::text[], 2, 'seconds', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, true, true, 'stretch_lunge', 'Hips, hamstrings and upper back in one move.', array['Step into a deep lunge, hands on the floor.', 'Drop your inside elbow toward your front foot.', 'Rotate and reach that arm to the ceiling.', 'Switch sides.']::text[], '{}'::text[]),
  ('hip_flexor_stretch', 'Kneeling Hip Flexor Stretch', 'legs', 'mobility', array['legs']::text[], 1, 'seconds', true, 'small', false, true, true, false, '{}'::text[], 3.0, null, true, false, 'stretch_lunge', 'Opens the front of the hips.', array['Kneel on one knee with a towel under it.', 'Tuck your pelvis and squeeze that glute.', 'Shift forward gently until you feel the front of the hip stretch.', 'Breathe and hold.']::text[], '{}'::text[]),
  ('standing_hamstring_stretch', 'Standing Hamstring Stretch', 'legs', 'mobility', array['legs']::text[], 1, 'seconds', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, false, 'good_morning', 'Hamstring stretch without the floor.', array['Place one heel forward, toes up, knee straight.', 'Hinge at the hips with a flat back.', 'Feel the back of the leg stretch.', 'Breathe and hold.']::text[], '{}'::text[]),
  ('standing_quad_stretch', 'Standing Quad Stretch', 'legs', 'mobility', array['legs']::text[], 1, 'seconds', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, false, 'quad_stretch', 'Stretch the front of the thigh.', array['Hold a wall for balance.', 'Pull one heel toward your glute.', 'Keep your knees together.', 'Tuck the pelvis slightly and hold.']::text[], '{}'::text[]),
  ('childs_pose', 'Child''s Pose', 'core', 'mobility', array['back']::text[], 1, 'seconds', false, 'small', false, true, true, false, '{}'::text[], 3.0, null, true, false, 'childs_pose', 'Rest and lengthen the back.', array['Kneel and sit back toward your heels.', 'Reach your arms forward on the floor.', 'Let your chest sink.', 'Breathe slowly into your back.']::text[], '{}'::text[]),
  ('thoracic_rotation', 'Open Book Rotation', 'upper', 'mobility', array['back']::text[], 1, 'seconds', true, 'small', false, true, false, false, '{}'::text[], 3.0, null, true, false, 'open_book', 'Upper back rotation lying on your side.', array['Lie on your side, knees bent, arms straight in front.', 'Open the top arm across to the other side.', 'Follow your hand with your eyes.', 'Return slowly. Switch sides halfway.']::text[], '{}'::text[]),
  ('deep_squat_hold', 'Deep Squat Hold', 'legs', 'mobility', array['legs']::text[], 2, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, false, 'deep_squat', 'Sit in the bottom of a squat to open hips and ankles.', array['Squat as deep as you comfortably can.', 'Push your knees out with your elbows.', 'Keep your heels down (hold a door frame if needed).', 'Breathe and relax.']::text[], '{}'::text[]),
  ('ankle_rocks', 'Ankle Rocks', 'legs', 'mobility', array['legs']::text[], 1, 'seconds', true, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, true, 'lunge', 'Improve ankle bend for better squats.', array['Stand in a split stance near a wall.', 'Drive your front knee forward over your toes.', 'Keep your heel down.', 'Rock in and out.']::text[], '{}'::text[]),
  ('hip_90_90', '90/90 Hip Switch', 'legs', 'mobility', array['legs']::text[], 2, 'seconds', false, 'small', false, true, false, false, '{}'::text[], 3.0, null, true, false, 'hip_90_90', 'Rotate the hips through their range.', array['Sit with both knees bent at 90°, one in front, one to the side.', 'Rotate both knees to the other side.', 'Stay tall.', 'Move slowly.']::text[], '{}'::text[]),
  ('chest_opener', 'Wall Chest Opener', 'upper', 'mobility', array['chest']::text[], 1, 'seconds', true, 'small', false, false, false, false, array['wall']::text[], 3.0, null, true, false, 'wall_angel', 'Stretch the chest after push work.', array['Place your forearm on a wall at shoulder height.', 'Turn your body away gently.', 'Feel the stretch across your chest.', 'Hold and switch sides.']::text[], '{}'::text[]),
  ('box_breathing', 'Box Breathing', 'core', 'mobility', array['core']::text[], 1, 'seconds', false, 'small', false, false, false, false, '{}'::text[], 3.0, null, true, false, 'breathing', 'Calm down and recover.', array['Breathe in for 4 seconds.', 'Hold for 4.', 'Breathe out for 4.', 'Hold for 4. Repeat.']::text[], '{}'::text[]),
  ('lying_hamstring_stretch', 'Lying Hamstring Stretch', 'legs', 'mobility', array['legs']::text[], 1, 'seconds', true, 'small', false, true, false, false, array['towel']::text[], 3.0, null, true, false, 'leg_raise', 'Use a towel around your foot to stretch the hamstring.', array['Lie on your back, towel around one foot.', 'Raise the straight leg until you feel a stretch.', 'Relax your shoulders.', 'Breathe and hold. Switch sides.']::text[], '{}'::text[])
on conflict (id) do update set
  name = excluded.name,
  area = excluded.area,
  pattern = excluded.pattern,
  focus = excluded.focus,
  difficulty = excluded.difficulty,
  unit = excluded.unit,
  per_side = excluded.per_side,
  space = excluded.space,
  impact = excluded.impact,
  floor_work = excluded.floor_work,
  knee_stress = excluded.knee_stress,
  wrist_stress = excluded.wrist_stress,
  props = excluded.props,
  seconds_per_rep = excluded.seconds_per_rep,
  family = excluded.family,
  mobility = excluded.mobility,
  warmup = excluded.warmup,
  demo = excluded.demo,
  summary = excluded.summary,
  cues = excluded.cues,
  mistakes = excluded.mistakes;

insert into public.skill_paths (id, name, area, goal_label, rep_min, rep_max, hold_min, hold_max, sort) values
  ('push', 'Push-up Path', 'upper', 'One-arm Push-up', 6, 15, 15, 45, 0),
  ('legs', 'Leg Path', 'legs', 'Pistol Squat', 8, 20, 20, 60, 1),
  ('core', 'Core Path', 'core', 'Tuck L-sit', 8, 15, 20, 90, 2),
  ('back', 'Back Path', 'upper', 'Arch Body Rock', 8, 15, 15, 45, 3),
  ('hips', 'Hip Path', 'legs', 'Single-leg Towel Curl', 8, 20, 20, 45, 4),
  ('conditioning', 'Conditioning Path', 'conditioning', 'Burpee Tuck Jump', 6, 15, 20, 50, 5)
on conflict (id) do update set
  name = excluded.name,
  area = excluded.area,
  goal_label = excluded.goal_label,
  rep_min = excluded.rep_min,
  rep_max = excluded.rep_max,
  hold_min = excluded.hold_min,
  hold_max = excluded.hold_max,
  sort = excluded.sort;

insert into public.skill_nodes (id, path_id, position, exercise_id, alternatives, milestone) values
  ('push:0', 'push', 0, 'wall_push_up', array['incline_push_up']::text[], false),
  ('push:1', 'push', 1, 'incline_push_up', array['knee_push_up']::text[], false),
  ('push:2', 'push', 2, 'knee_push_up', array['incline_push_up']::text[], false),
  ('push:3', 'push', 3, 'push_up', array['incline_push_up']::text[], true),
  ('push:4', 'push', 4, 'diamond_push_up', '{}'::text[], false),
  ('push:5', 'push', 5, 'decline_push_up', array['pike_push_up']::text[], false),
  ('push:6', 'push', 6, 'archer_push_up', '{}'::text[], true),
  ('push:7', 'push', 7, 'incline_one_arm_push_up', array['pseudo_planche_push_up']::text[], false),
  ('push:8', 'push', 8, 'one_arm_push_up', '{}'::text[], true),
  ('legs:0', 'legs', 0, 'sit_to_stand', array['quarter_squat']::text[], false),
  ('legs:1', 'legs', 1, 'bodyweight_squat', array['sit_to_stand']::text[], true),
  ('legs:2', 'legs', 2, 'pause_squat', '{}'::text[], false),
  ('legs:3', 'legs', 3, 'split_squat', array['pause_squat']::text[], true),
  ('legs:4', 'legs', 4, 'tempo_split_squat', array['pause_squat']::text[], false),
  ('legs:5', 'legs', 5, 'bulgarian_split_squat', array['tempo_split_squat']::text[], true),
  ('legs:6', 'legs', 6, 'skater_squat', array['bulgarian_split_squat', 'tempo_split_squat']::text[], false),
  ('legs:7', 'legs', 7, 'assisted_pistol_squat', array['box_pistol_squat', 'skater_squat']::text[], false),
  ('legs:8', 'legs', 8, 'box_pistol_squat', array['assisted_pistol_squat']::text[], false),
  ('legs:9', 'legs', 9, 'pistol_squat', '{}'::text[], true),
  ('core:0', 'core', 0, 'dead_bug', array['standing_knee_to_elbow']::text[], false),
  ('core:1', 'core', 1, 'plank', array['wall_plank']::text[], true),
  ('core:2', 'core', 2, 'long_lever_plank', array['wall_plank']::text[], false),
  ('core:3', 'core', 3, 'side_plank', array['standing_side_crunch']::text[], true),
  ('core:4', 'core', 4, 'hollow_body_hold', '{}'::text[], true),
  ('core:5', 'core', 5, 'hollow_body_rock', '{}'::text[], false),
  ('core:6', 'core', 6, 'v_up', '{}'::text[], false),
  ('core:7', 'core', 7, 'tuck_l_sit', array['v_up']::text[], true),
  ('back:0', 'back', 0, 'prone_y_raise', array['wall_angel']::text[], false),
  ('back:1', 'back', 1, 'prone_ytw', array['towel_pull_apart']::text[], false),
  ('back:2', 'back', 2, 'superman_hold', array['bent_over_ytw']::text[], true),
  ('back:3', 'back', 3, 'reverse_snow_angel', array['towel_row_hold']::text[], false),
  ('back:4', 'back', 4, 'prone_swimmer', array['towel_row_hold']::text[], false),
  ('back:5', 'back', 5, 'towel_floor_pull', array['prone_swimmer']::text[], true),
  ('back:6', 'back', 6, 'arch_body_hold', '{}'::text[], false),
  ('back:7', 'back', 7, 'arch_body_rock', '{}'::text[], true),
  ('hips:0', 'hips', 0, 'glute_bridge', array['standing_glute_kickback']::text[], false),
  ('hips:1', 'hips', 1, 'glute_bridge_march', array['good_morning']::text[], false),
  ('hips:2', 'hips', 2, 'b_stance_glute_bridge', array['good_morning']::text[], false),
  ('hips:3', 'hips', 3, 'single_leg_glute_bridge', array['single_leg_rdl']::text[], true),
  ('hips:4', 'hips', 4, 'hip_thrust', array['single_leg_glute_bridge']::text[], false),
  ('hips:5', 'hips', 5, 'single_leg_rdl', '{}'::text[], true),
  ('hips:6', 'hips', 6, 'single_leg_hip_thrust', array['single_leg_rdl']::text[], false),
  ('hips:7', 'hips', 7, 'hamstring_walkout', array['single_leg_rdl']::text[], false),
  ('hips:8', 'hips', 8, 'towel_leg_curl', array['hamstring_walkout']::text[], true),
  ('hips:9', 'hips', 9, 'single_leg_towel_curl', '{}'::text[], true),
  ('conditioning:0', 'conditioning', 0, 'march_in_place', '{}'::text[], false),
  ('conditioning:1', 'conditioning', 1, 'step_jack', '{}'::text[], false),
  ('conditioning:2', 'conditioning', 2, 'shadow_boxing', array['step_jack']::text[], false),
  ('conditioning:3', 'conditioning', 3, 'mountain_climber', array['speed_squat']::text[], true),
  ('conditioning:4', 'conditioning', 4, 'jumping_jack', array['low_impact_skater', 'shadow_boxing']::text[], false),
  ('conditioning:5', 'conditioning', 5, 'step_back_burpee', array['speed_squat']::text[], false),
  ('conditioning:6', 'conditioning', 6, 'burpee_no_push_up', array['step_back_burpee', 'speed_squat']::text[], true),
  ('conditioning:7', 'conditioning', 7, 'burpee', array['step_back_burpee', 'speed_squat']::text[], false),
  ('conditioning:8', 'conditioning', 8, 'burpee_tuck_jump', array['burpee', 'step_back_burpee', 'speed_squat']::text[], true)
on conflict (id) do update set
  path_id = excluded.path_id,
  position = excluded.position,
  exercise_id = excluded.exercise_id,
  alternatives = excluded.alternatives,
  milestone = excluded.milestone;

insert into public.nutrition_items (id, name, aka, category, serving, kcal, protein, carbs, fat, price_ghs, tips) values
  ('eggs', 'Eggs', null, 'protein', '2 large eggs', 143, 12.6, 0.7, 9.5, 5.0, array['One of the cheapest complete proteins you can buy.', 'Boil a batch for quick breakfasts and snacks.', 'Eat the yolk — it carries half the protein and most of the vitamins.']::text[]),
  ('beans_red_red', 'Red-red', 'Black-eyed bean stew', 'protein', '1 bowl (250 g)', 350, 13.0, 40.0, 15.0, 8.0, array['Beans give protein and fibre that keep you full.', 'Go lighter on the palm oil when cutting body fat.', 'Add an egg or sardines to push the protein past 20 g.']::text[]),
  ('sardines', 'Sardines', null, 'protein', '1 tin (≈ 90 g drained)', 190, 21.0, 0.0, 11.0, 15.0, array['Protein plus omega-3 fats in one tin.', 'Eat the soft bones for extra calcium.', 'Great with kenkey, bread or gari.']::text[]),
  ('tuna', 'Tuna', null, 'protein', '1 tin (≈ 110 g drained)', 150, 27.0, 0.0, 4.0, 22.0, array['Choose tuna in water or brine for fewer calories.', 'Mix with tomato and onion for a quick salad.']::text[]),
  ('chicken', 'Chicken', null, 'protein', 'Thigh + drumstick (150 g)', 330, 36.0, 0.0, 20.0, 20.0, array['Remove the skin to cut the fat by about a third.', 'Grill or boil instead of deep-frying.']::text[]),
  ('tilapia', 'Tilapia', null, 'protein', '1 medium fish (150 g edible)', 190, 39.0, 0.0, 4.0, 35.0, array['Very lean, very high protein.', 'Grilled tilapia with banku is a strong post-workout meal.']::text[]),
  ('mackerel', 'Mackerel', '"Salmon" / smoked fish', 'protein', '100 g', 250, 22.0, 0.0, 17.0, 15.0, array['Rich in healthy fats.', 'Smoked fish adds protein to any stew for little money.']::text[]),
  ('milk', 'Milk', null, 'protein', '1 cup (250 ml)', 150, 8.0, 12.0, 8.0, 6.0, array['Powdered milk is often the cheapest per gram of protein.', 'Add to oats or tea for easy protein.']::text[]),
  ('wagashi', 'Wagashi', 'Wagashie cheese', 'protein', '100 g', 260, 20.0, 3.0, 18.0, 10.0, array['A local cheese that is high in protein.', 'Grill or add to stew instead of deep-frying.']::text[]),
  ('soya_chunks', 'Soya chunks', null, 'protein', '50 g dry', 170, 26.0, 16.0, 0.5, 4.0, array['One of the best protein-per-cedi foods.', 'Soak, squeeze and cook in stew like meat.']::text[]),
  ('rice', 'Rice', null, 'carbs', '1 cup cooked (160 g)', 205, 4.3, 45.0, 0.4, 4.0, array['Match the portion to your activity — bigger on training days.', 'Pair with beans for more protein.']::text[]),
  ('oats', 'Oats', null, 'carbs', '40 g dry', 150, 5.0, 27.0, 2.5, 3.0, array['Slow energy that keeps you full.', 'Cook with milk and top with groundnuts for a protein breakfast.']::text[]),
  ('plantain', 'Plantain', null, 'carbs', '1 medium, boiled (180 g)', 210, 2.0, 55.0, 0.3, 5.0, array['Boiled or roasted plantain has far fewer calories than fried.', 'Unripe plantain keeps you fuller.']::text[]),
  ('kelewele', 'Kelewele', null, 'carbs', '1 small bowl (150 g)', 300, 2.0, 45.0, 13.0, 10.0, array['Delicious, but fried — keep it as an occasional treat.', 'Eat with groundnuts for some protein.']::text[]),
  ('yam', 'Yam', null, 'carbs', '2 boiled slices (200 g)', 230, 3.0, 55.0, 0.3, 6.0, array['Great fuel before training.', 'Pair with kontomire stew and egg for a complete meal.']::text[]),
  ('sweet_potato', 'Sweet potato', null, 'carbs', '200 g', 180, 4.0, 41.0, 0.3, 4.0, array['Packed with vitamin A.', 'Boil or roast with the skin on for more fibre.']::text[]),
  ('gari', 'Gari', null, 'carbs', '50 g dry', 180, 0.5, 43.0, 0.3, 2.0, array['Cheap energy but almost no protein.', 'Soak with milk and groundnuts to make it a better meal.']::text[]),
  ('kenkey', 'Kenkey', null, 'carbs', '1 ball (300 g)', 400, 8.0, 85.0, 3.0, 5.0, array['Fermented corn is easy on the stomach for many people.', 'Classic with fish and pepper for protein.']::text[]),
  ('banku', 'Banku', null, 'carbs', '1 ball (300 g)', 350, 7.0, 75.0, 2.0, 5.0, array['Pair with okro soup and fish or tilapia.', 'Half a ball is plenty on rest days.']::text[]),
  ('waakye', 'Waakye', null, 'meals', '1 plate (300 g)', 450, 14.0, 85.0, 5.0, 12.0, array['Rice and beans together make better protein.', 'Add egg or fish; go easy on spaghetti and gari.']::text[]),
  ('kontomire', 'Kontomire stew', 'Cocoyam leaf stew with egg', 'meals', '1 bowl (250 g)', 220, 10.0, 10.0, 15.0, 10.0, array['Iron-rich leafy greens.', 'Add more egg or wagashi for extra protein.']::text[]),
  ('garden_eggs', 'Garden eggs', null, 'vegetables', '100 g', 25, 1.0, 6.0, 0.0, 3.0, array['Very low calorie, adds volume to stews.', 'Great for filling up while losing fat.']::text[]),
  ('okro', 'Okro', null, 'vegetables', '100 g', 33, 2.0, 7.0, 0.2, 3.0, array['High in fibre.', 'Okro soup with fish is a light, high-protein dinner.']::text[]),
  ('tomato_onion', 'Tomatoes & onions', null, 'vegetables', '100 g', 25, 1.0, 5.0, 0.0, 5.0, array['The base of most stews — use plenty.', 'Fresh pepper sauce adds flavour for almost no calories.']::text[]),
  ('cabbage_carrot', 'Cabbage & carrots', null, 'vegetables', '150 g', 45, 1.5, 10.0, 0.2, 4.0, array['Cheap and crunchy — perfect for a quick salad.', 'Add to fried rice or stew to bulk up the meal.']::text[]),
  ('banana', 'Banana', null, 'fruit', '1 medium', 105, 1.3, 27.0, 0.4, 1.5, array['Quick energy before a workout.', 'Slice into oats for breakfast.']::text[]),
  ('orange', 'Orange', null, 'fruit', '1 medium', 60, 1.2, 15.0, 0.2, 1.5, array['Vitamin C and water in one.', 'A far better choice than soft drinks.']::text[]),
  ('pawpaw', 'Pawpaw', null, 'fruit', '1 cup (150 g)', 60, 0.7, 16.0, 0.4, 3.0, array['Good for digestion.', 'Low calorie and sweet.']::text[]),
  ('pineapple', 'Pineapple', null, 'fruit', '1 cup (165 g)', 82, 0.9, 22.0, 0.2, 4.0, array['Sweet and hydrating.', 'Great after training.']::text[]),
  ('watermelon', 'Watermelon', null, 'fruit', '2 slices (300 g)', 90, 1.8, 23.0, 0.5, 4.0, array['Over 90% water — great on hot days.', 'Low calorie for how much you get.']::text[]),
  ('avocado', 'Avocado', null, 'fats', 'Half (100 g)', 160, 2.0, 9.0, 15.0, 4.0, array['Healthy fats that keep you full.', 'Mash on bread instead of margarine.']::text[]),
  ('groundnuts', 'Groundnuts', null, 'fats', '1 handful (30 g)', 170, 7.5, 5.0, 14.0, 3.0, array['Protein and healthy fats, but calorie-dense — measure a handful.', 'Groundnut soup with fish or chicken is a great protein meal.']::text[])
on conflict (id) do update set
  name = excluded.name,
  aka = excluded.aka,
  category = excluded.category,
  serving = excluded.serving,
  kcal = excluded.kcal,
  protein = excluded.protein,
  carbs = excluded.carbs,
  fat = excluded.fat,
  price_ghs = excluded.price_ghs,
  tips = excluded.tips;

insert into public.challenges (id, title, tagline, description, daily_prompt, check_type, days_required, daily_target, protein_target, price_limit_ghs, tips) values
  ('protein_20', 'GH₵20 Protein Challenge', 'Big protein, small budget', 'Build a protein-focused meal with at least 25 g of protein for GH₵20 or less, using everyday foods. Do it on 7 different days.', 'Build today''s GH₵20 meal', 'mealBuilder', 7, 1, 25.0, 20.0, array['Eggs, sardines, beans, soya chunks and groundnuts give the most protein per cedi.', 'Combine a cheap carb (gari, kenkey, rice) with one strong protein.', 'Set your local prices in the food database so the totals match your market.']::text[]),
  ('water_7', '7-Day Water Challenge', 'Build a hydration habit', 'Drink your daily water target on 7 days. Tap a glass each time you finish one.', 'Glasses of water today', 'counter', 7, 8, 0.0, 0.0, array['Keep a filled bottle where you can see it.', 'Drink a glass as soon as you wake up.', 'Drink more on hot days and training days.']::text[]),
  ('breakfast_7', '7-Day Breakfast Challenge', 'Start the day strong', 'Eat a breakfast with a protein source (eggs, milk, groundnuts, beans…) on 7 days.', 'Did you eat a protein breakfast today?', 'yesNo', 7, 1, 0.0, 0.0, array['Boil eggs the night before.', 'Oats with milk and groundnuts takes 5 minutes.', 'Koko with groundnuts and an egg beats koko alone.']::text[]),
  ('no_soda_7', 'No Soft Drink Challenge', 'Cut the sugar', 'Go 7 days without sugary soft drinks or sweetened juice.', 'Soft-drink free today?', 'yesNo', 7, 1, 0.0, 0.0, array['A single 500 ml soft drink can hold more than 10 teaspoons of sugar.', 'Swap for water with lime, or sobolo without added sugar.', 'Check the label on "juice" drinks too.']::text[])
on conflict (id) do update set
  title = excluded.title,
  tagline = excluded.tagline,
  description = excluded.description,
  daily_prompt = excluded.daily_prompt,
  check_type = excluded.check_type,
  days_required = excluded.days_required,
  daily_target = excluded.daily_target,
  protein_target = excluded.protein_target,
  price_limit_ghs = excluded.price_limit_ghs,
  tips = excluded.tips;

insert into public.achievements (id, title, description, tier, icon, target) values
  ('first_rep', 'FIRST REP', 'Completed your first workout.', 'lavender', 'bolt', 1),
  ('seven_days_strong', '7 DAYS STRONG', 'Completed every planned workout in a training week.', 'lavender', 'calendar', 1),
  ('first_pr', 'FIRST PR', 'Set your first personal record.', 'lime', 'trophy', 1),
  ('hundred_push_ups', '100 PUSH-UPS', 'Completed 100 push-ups across your workouts.', 'lime', 'push', 100),
  ('thirty_workouts', '30 WORKOUTS', 'Completed 30 workouts.', 'ember', 'flame', 30),
  ('core_builder', 'CORE BUILDER', 'Completed 20 core sessions.', 'lime', 'core', 20),
  ('bodyforge', 'BODYFORGE', 'Completed the full 12-week journey.', 'ember', 'crown', 1),
  ('skill_unlocked', 'LEVEL UP', 'Unlocked a harder variation on a skill path.', 'lime', 'unlock', 1),
  ('path_master', 'PATH MASTER', 'Reached the final skill on any path.', 'ember', 'summit', 1),
  ('ten_prs', 'RECORD BREAKER', 'Set 10 personal records.', 'lime', 'trophy', 10),
  ('thousand_squats', '1,000 SQUATS', 'Completed 1,000 squat-family reps.', 'lime', 'legs', 1000),
  ('plank_two_minutes', 'IRON CORE', 'Held a plank for 2 minutes.', 'lime', 'timer', 1),
  ('something_better', 'SOMETHING > NOTHING', 'Completed a quick session on a low-motivation day.', 'lavender', 'spark', 1),
  ('recovery_respected', 'RECOVERY RESPECTED', 'Completed 5 recovery sessions.', 'lavender', 'leaf', 5),
  ('comeback', 'THE COMEBACK', 'Came back and trained after 7+ days off.', 'lavender', 'return', 1),
  ('phase_one', 'HABIT BUILT', 'Finished phase 1 of the journey: Build the Habit.', 'lavender', 'flag', 1),
  ('halfway_forged', 'HALFWAY FORGED', 'Completed 6 weeks of the journey.', 'lavender', 'half', 1),
  ('phase_two', 'BODY BUILT', 'Finished phase 2 of the journey: Build the Body.', 'lime', 'flag', 1),
  ('measured', 'MEASURED', 'Logged your first body measurement.', 'lavender', 'ruler', 1),
  ('consistent_month', 'CONSISTENT MONTH', '80%+ consistency across 30 days with at least 8 workouts.', 'ember', 'calendar', 1),
  ('hydrated', 'HYDRATED', 'Completed the 7-Day Water Challenge.', 'lavender', 'drop', 1),
  ('budget_protein', 'BUDGET PROTEIN', 'Completed the GH₵20 Protein Challenge.', 'lime', 'food', 1),
  ('hundred_workouts', '100 WORKOUTS', 'Completed 100 workouts.', 'ember', 'flame', 100)
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  tier = excluded.tier,
  icon = excluded.icon,
  target = excluded.target;

commit;

-- Check: this should show exercises 114, skill_nodes 54, foods 32, challenges 4, achievements 23.
select (select count(*) from public.exercises) as exercises,
       (select count(*) from public.skill_nodes) as skill_nodes,
       (select count(*) from public.nutrition_items) as foods,
       (select count(*) from public.challenges) as challenges,
       (select count(*) from public.achievements) as achievements,
       'BODYFORGE database ready' as status;
