// Built-in exercise catalog. This is the single source of truth: the app
// reads it directly (works offline from first launch) and
// `tool/generate_seed.dart` turns it into `supabase/seed.sql`.
import '../models/enums.dart';
import '../models/exercise.dart';

const _upper = {MuscleFocus.chest, MuscleFocus.arms, MuscleFocus.shoulders};
const _back = {MuscleFocus.back, MuscleFocus.shoulders};
const _legs = {MuscleFocus.legs};
const _core = {MuscleFocus.core};
const _full = {MuscleFocus.fullBody};

const List<Exercise> kExercises = [
  // ───────────────────────────── PUSH ─────────────────────────────
  Exercise(
    id: 'wall_push_up', name: 'Wall Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: _upper, difficulty: 1, demo: 'wall_push_up', props: {Prop.wall}, floorWork: false, family: 'push_up',
    summary: 'The gentlest push-up. Builds the pattern with very little load.',
    cues: ['Stand an arm\'s length from a wall, hands at chest height, shoulder-width apart.',
      'Keep your body in one straight line from head to heels.',
      'Bend your elbows to bring your chest toward the wall, elbows at about 45°.',
      'Press the wall away until your arms are straight.'],
    mistakes: ['Letting the hips sag forward', 'Flaring elbows straight out'],
  ),
  Exercise(
    id: 'incline_push_up', name: 'Incline Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: _upper, difficulty: 2, demo: 'incline_push_up', props: {Prop.elevated}, floorWork: false, wristStress: true,
    family: 'push_up',
    summary: 'Hands on a sturdy bed edge, sofa or chair. The higher the surface, the easier it is.',
    cues: ['Place your hands on a stable raised surface, slightly wider than your shoulders.',
      'Walk your feet back until your body is a straight plank.',
      'Lower your chest to the edge with control.',
      'Push back up, squeezing your glutes the whole time.'],
    mistakes: ['Using a chair that can slide — brace it against a wall', 'Piking the hips up'],
  ),
  Exercise(
    id: 'knee_push_up', name: 'Knee Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: _upper, difficulty: 3, demo: 'knee_push_up', wristStress: true, kneeStress: true, family: 'push_up',
    summary: 'A full-range push-up with a shorter lever.',
    cues: ['Kneel with a towel under your knees, hands just wider than shoulders.',
      'Keep a straight line from knees to head — hips forward, not bent.',
      'Lower until your chest is a fist\'s height from the floor.',
      'Press the floor away and fully straighten your arms.'],
    mistakes: ['Hips bent (half-kneeling)', 'Head dropping before the chest'],
  ),
  Exercise(
    id: 'push_up', name: 'Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: _upper, difficulty: 4, demo: 'push_up', wristStress: true, family: 'push_up',
    summary: 'The foundation of upper-body bodyweight strength.',
    cues: ['Hands under shoulders, feet together, body in a straight line.',
      'Brace your abs and squeeze your glutes.',
      'Lower as one unit until your chest nearly touches the floor, elbows at 45°.',
      'Push the floor away until your arms are straight.'],
    mistakes: ['Sagging hips', 'Partial reps', 'Elbows flared to 90°'],
  ),
  Exercise(
    id: 'diamond_push_up', name: 'Diamond Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: {MuscleFocus.arms, MuscleFocus.chest}, difficulty: 5, demo: 'push_up', wristStress: true,
    family: 'push_up',
    summary: 'Hands close together to shift the work to the triceps.',
    cues: ['Make a diamond with your thumbs and index fingers under your chest.',
      'Keep your elbows tucked close to your ribs.',
      'Lower until your chest touches your hands.',
      'Press up without letting your hips lead.'],
    mistakes: ['Elbows flaring wide', 'Shortening the range'],
  ),
  Exercise(
    id: 'decline_push_up', name: 'Decline Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: {MuscleFocus.chest, MuscleFocus.shoulders}, difficulty: 6, demo: 'decline_push_up',
    props: {Prop.elevated}, wristStress: true, family: 'push_up',
    summary: 'Feet on a bed, sofa or chair to load the upper chest and shoulders.',
    cues: ['Put your feet on a stable raised surface, hands on the floor under your shoulders.',
      'Keep your body straight — don\'t let the hips sag.',
      'Lower your forehead-to-chest area toward the floor.',
      'Press back up to straight arms.'],
    mistakes: ['Hips piking up to make it easier'],
  ),
  Exercise(
    id: 'pike_push_up', name: 'Pike Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: {MuscleFocus.shoulders, MuscleFocus.arms}, difficulty: 6, demo: 'pike_push_up', wristStress: true,
    summary: 'Hips high in an upside-down V to train the shoulders.',
    cues: ['Start in a push-up, then walk your feet in and lift your hips high.',
      'Keep your arms straight and head between your arms.',
      'Bend your elbows to lower the top of your head toward the floor in front of your hands.',
      'Press back up to the V shape.'],
    mistakes: ['Dropping the hips into a push-up', 'Elbows flaring out'],
  ),
  Exercise(
    id: 'archer_push_up', name: 'Archer Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: _upper, difficulty: 7, demo: 'push_up', wristStress: true, perSide: true, family: 'push_up',
    summary: 'A wide push-up that shifts most of the load to one arm.',
    cues: ['Set your hands very wide, fingers turned slightly out.',
      'Lower toward one hand while the other arm straightens out to the side.',
      'Keep your hips square to the floor.',
      'Push back to the centre and alternate sides.'],
    mistakes: ['Twisting the hips', 'Bending the straight arm'],
  ),
  Exercise(
    id: 'pseudo_planche_push_up', name: 'Pseudo Planche Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: {MuscleFocus.shoulders, MuscleFocus.chest}, difficulty: 8, demo: 'push_up', wristStress: true,
    family: 'push_up',
    summary: 'Hands by the hips and shoulders leaning forward — a serious strength builder.',
    cues: ['Place your hands beside your lower ribs, fingers turned out.',
      'Lean your shoulders forward past your hands.',
      'Lower with control while keeping the forward lean.',
      'Press up and keep the shoulders protracted.'],
    mistakes: ['Losing the lean at the bottom'],
  ),
  Exercise(
    id: 'incline_one_arm_push_up', name: 'Incline One-arm Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: _upper, difficulty: 8, demo: 'incline_push_up', props: {Prop.elevated}, floorWork: false,
    wristStress: true, perSide: true, family: 'push_up',
    summary: 'One-arm push-up with the hand on a raised surface.',
    cues: ['Place one hand on a sturdy raised surface, feet wide for balance.',
      'Put your free hand behind your back.',
      'Lower your chest toward the hand, keeping your hips square.',
      'Press up without twisting.'],
    mistakes: ['Rotating the torso open'],
  ),
  Exercise(
    id: 'one_arm_push_up', name: 'One-arm Push-up', area: Area.upper, pattern: MovementPattern.push,
    focus: _upper, difficulty: 10, demo: 'push_up', wristStress: true, perSide: true, family: 'push_up',
    summary: 'The top of the push-up path.',
    cues: ['Feet wider than shoulders, one hand under your chest.',
      'Brace hard — glutes, abs and the free-side lat.',
      'Lower slowly until your chest is just above the floor.',
      'Drive up without letting the hips rotate.'],
    mistakes: ['Twisting through the torso'],
  ),
  Exercise(
    id: 'chair_dip', name: 'Chair Dip', area: Area.upper, pattern: MovementPattern.push,
    focus: {MuscleFocus.arms, MuscleFocus.chest}, difficulty: 4, demo: 'dip', props: {Prop.elevated},
    floorWork: false, wristStress: true,
    summary: 'Triceps builder on a sturdy chair, bed edge or sofa.',
    cues: ['Sit on the edge, hands beside your hips, fingers forward.',
      'Slide your hips off the edge, knees bent.',
      'Lower until your elbows reach about 90°, keeping them pointed back.',
      'Press up to straight arms.'],
    mistakes: ['Going too deep and rolling the shoulders forward', 'Using a chair on wheels'],
  ),
  Exercise(
    id: 'shoulder_tap', name: 'Plank Shoulder Tap', area: Area.core, pattern: MovementPattern.coreRotation,
    focus: {MuscleFocus.core, MuscleFocus.shoulders}, difficulty: 3, demo: 'plank_tap', wristStress: true,
    perSide: true,
    summary: 'Anti-rotation core work in a high plank.',
    cues: ['High plank with feet slightly wider than hips.',
      'Lift one hand and tap the opposite shoulder.',
      'Keep your hips as still as possible.',
      'Alternate slowly.'],
    mistakes: ['Rocking the hips side to side'],
  ),
  Exercise(
    id: 'plank_up_down', name: 'Plank Up-down', area: Area.upper, pattern: MovementPattern.push,
    focus: {MuscleFocus.arms, MuscleFocus.core}, difficulty: 5, demo: 'plank_tap', wristStress: true,
    summary: 'Move between forearm and high plank.',
    cues: ['Start in a forearm plank.',
      'Press up one hand at a time into a high plank.',
      'Lower back down one forearm at a time.',
      'Alternate the leading arm each rep.'],
    mistakes: ['Swaying the hips'],
  ),
  Exercise(
    id: 'towel_curl_hold', name: 'Towel Curl Hold', area: Area.upper, pattern: MovementPattern.pull,
    focus: {MuscleFocus.arms}, difficulty: 2, demo: 'towel_row', props: {Prop.towel}, floorWork: false,
    unit: ExerciseUnit.seconds,
    summary: 'Isometric biceps work: pull up on a towel trapped under your foot.',
    cues: ['Stand on the middle of a towel, holding both ends.',
      'Bend your elbows to 90°.',
      'Pull upward as hard as you can without moving — the towel won\'t let you.',
      'Breathe steadily and hold.'],
    mistakes: ['Holding your breath', 'Leaning back'],
  ),
  Exercise(
    id: 'wall_handstand_hold', name: 'Wall Handstand Hold', area: Area.upper, pattern: MovementPattern.push,
    focus: {MuscleFocus.shoulders}, difficulty: 8, demo: 'pike_push_up', props: {Prop.wall},
    wristStress: true, unit: ExerciseUnit.seconds,
    summary: 'Chest-to-wall handstand for shoulder strength.',
    cues: ['Face away from the wall in a push-up position, feet against the wall.',
      'Walk your feet up and hands in until your body is steep and straight.',
      'Push tall through your shoulders.',
      'Walk down with control before you tire.'],
    mistakes: ['Arching the lower back', 'Staying up until failure'],
  ),

  // ───────────────────────────── BACK / PULL ─────────────────────────────
  Exercise(
    id: 'prone_y_raise', name: 'Prone Y Raise', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 1, demo: 'prone_raise',
    summary: 'Wakes up the upper back and rear shoulders.',
    cues: ['Lie face down, arms overhead in a Y, thumbs up.',
      'Squeeze your shoulder blades down and back.',
      'Lift your arms a few centimetres off the floor.',
      'Pause for a second, then lower.'],
    mistakes: ['Shrugging toward the ears'],
  ),
  Exercise(
    id: 'prone_ytw', name: 'Prone Y-T-W', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 2, demo: 'prone_raise',
    summary: 'Three arm positions to strengthen the whole upper back.',
    cues: ['Lie face down with your forehead on a towel.',
      'Raise your arms in a Y, lower; then a T, lower; then a W, lower.',
      'Lead with your shoulder blades, not your hands.',
      'That\'s one rep.'],
    mistakes: ['Lifting the chest high instead of the arms'],
  ),
  Exercise(
    id: 'superman_hold', name: 'Superman Hold', area: Area.upper, pattern: MovementPattern.hinge,
    focus: {MuscleFocus.back, MuscleFocus.core}, difficulty: 3, demo: 'superman', unit: ExerciseUnit.seconds,
    summary: 'Holds the whole back line strong.',
    cues: ['Lie face down, arms overhead.',
      'Lift arms, chest and legs off the floor together.',
      'Keep your neck long — look at the floor.',
      'Hold and breathe.'],
    mistakes: ['Cranking the neck up'],
  ),
  Exercise(
    id: 'towel_row_hold', name: 'Towel Row Hold', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 3, demo: 'towel_row', props: {Prop.towel}, floorWork: false,
    unit: ExerciseUnit.seconds,
    summary: 'Isometric row: pull a towel apart around your feet.',
    cues: ['Sit tall with legs straight and a towel looped around your feet.',
      'Pull the ends toward your ribs, elbows back.',
      'Squeeze your shoulder blades together as hard as you can.',
      'Hold without leaning back.'],
    mistakes: ['Rounding the upper back'],
  ),
  Exercise(
    id: 'reverse_snow_angel', name: 'Reverse Snow Angel', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 4, demo: 'prone_raise',
    summary: 'A big sweeping arc that builds the upper back.',
    cues: ['Lie face down, arms by your sides, palms down, hands slightly lifted.',
      'Sweep your arms in a wide arc overhead without touching the floor.',
      'Sweep back to your hips.',
      'Keep your chest down and move slowly.'],
    mistakes: ['Letting the hands touch down to rest'],
  ),
  Exercise(
    id: 'prone_swimmer', name: 'Prone Swimmer', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 5, demo: 'prone_raise',
    summary: 'Continuous upper-back endurance.',
    cues: ['Lie face down with chest and arms slightly lifted.',
      'Pull your elbows down to your ribs like a pull-up.',
      'Reach back overhead.',
      'Keep everything off the floor for the whole set.'],
    mistakes: ['Dropping the chest between reps'],
  ),
  Exercise(
    id: 'towel_floor_pull', name: 'Towel Floor Pull', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 6, demo: 'floor_pull', props: {Prop.towel}, space: SpaceNeed.medium,
    summary: 'Lie on a towel on a smooth floor and pull yourself forward with your forearms.',
    cues: ['Lie face down on a towel on a smooth floor (tile or wood).',
      'Reach forward and plant your forearms.',
      'Pull your body forward by driving your elbows down and back.',
      'Reset and repeat.'],
    mistakes: ['Pushing with the feet'],
  ),
  Exercise(
    id: 'arch_body_hold', name: 'Arch Body Hold', area: Area.upper, pattern: MovementPattern.hinge,
    focus: {MuscleFocus.back, MuscleFocus.core}, difficulty: 7, demo: 'superman', unit: ExerciseUnit.seconds,
    summary: 'The mirror of the hollow hold — a strong, tight banana shape face down.',
    cues: ['Lie face down, arms overhead, legs together.',
      'Lift arms, chest and legs into a smooth arch.',
      'Squeeze glutes and reach long.',
      'Hold without bending the knees.'],
    mistakes: ['Bending the knees to lift higher'],
  ),
  Exercise(
    id: 'arch_body_rock', name: 'Arch Body Rock', area: Area.upper, pattern: MovementPattern.hinge,
    focus: {MuscleFocus.back, MuscleFocus.core}, difficulty: 8, demo: 'superman',
    summary: 'Rock in a locked arch hold.',
    cues: ['Get into a tight arch hold.',
      'Rock forward and back as one unit.',
      'Never let the shape collapse.',
      'Keep your breathing steady.'],
    mistakes: ['Breaking the shape'],
  ),
  Exercise(
    id: 'wall_angel', name: 'Wall Angel', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 1, demo: 'wall_angel', props: {Prop.wall}, floorWork: false, mobility: true,
    warmup: true,
    summary: 'Posture and shoulder mobility against a wall.',
    cues: ['Stand with your back, head and hips against a wall.',
      'Raise your arms in a W, backs of hands on the wall.',
      'Slide them up to a Y and back down.',
      'Keep your ribs down.'],
    mistakes: ['Arching the lower back off the wall'],
  ),
  Exercise(
    id: 'towel_pull_apart', name: 'Towel Pull-apart', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 2, demo: 'towel_row', props: {Prop.towel}, floorWork: false,
    unit: ExerciseUnit.seconds,
    summary: 'Standing isometric for the upper back.',
    cues: ['Hold a towel at shoulder height, arms straight.',
      'Try to pull the towel apart.',
      'Squeeze your shoulder blades together.',
      'Hold and breathe.'],
    mistakes: ['Shrugging'],
  ),
  Exercise(
    id: 'bent_over_ytw', name: 'Bent-over Y-T-W', area: Area.upper, pattern: MovementPattern.pull,
    focus: _back, difficulty: 3, demo: 'good_morning', floorWork: false,
    summary: 'Upper-back raises from a standing hip hinge — no floor needed.',
    cues: ['Hinge at the hips with a flat back, knees soft.',
      'Raise your arms in a Y, then T, then W.',
      'Squeeze your shoulder blades each time.',
      'Keep your back flat throughout.'],
    mistakes: ['Rounding the back'],
  ),

  // ───────────────────────────── LEGS ─────────────────────────────
  Exercise(
    id: 'sit_to_stand', name: 'Sit-to-Stand', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 1, demo: 'sit_to_stand', props: {Prop.elevated}, floorWork: false,
    family: 'squat',
    summary: 'Squat to a chair or bed — the safest way to learn the squat.',
    cues: ['Stand in front of a sturdy chair or bed, feet shoulder-width.',
      'Push your hips back and sit down with control.',
      'Lightly touch the seat — don\'t collapse onto it.',
      'Drive through your whole foot to stand tall.'],
    mistakes: ['Knees caving in', 'Rocking forward to stand'],
  ),
  Exercise(
    id: 'quarter_squat', name: 'Quarter Squat', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 1, demo: 'squat', floorWork: false, family: 'squat',
    summary: 'A shallow squat for limited mobility days.',
    cues: ['Feet shoulder-width, arms forward for balance.',
      'Bend knees and hips a quarter of the way down.',
      'Keep your heels planted and chest up.',
      'Stand tall and squeeze your glutes.'],
    mistakes: ['Knees drifting inward'],
  ),
  Exercise(
    id: 'bodyweight_squat', name: 'Squat', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 2, demo: 'squat', floorWork: false, family: 'squat',
    summary: 'The fundamental lower-body movement.',
    cues: ['Feet shoulder-width, toes turned out slightly.',
      'Sit your hips back and down, knees tracking over your toes.',
      'Go as low as you can with heels down and a proud chest.',
      'Drive up through your whole foot.'],
    mistakes: ['Heels lifting', 'Knees caving in'],
  ),
  Exercise(
    id: 'pause_squat', name: 'Pause Squat', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 3, demo: 'squat', floorWork: false, secondsPerRep: 5, family: 'squat',
    summary: 'Squat with a 2-second pause at the bottom.',
    cues: ['Squat down with control.',
      'Hold the bottom position for two full seconds, staying tight.',
      'Drive up hard.',
      'Reset your breath at the top.'],
    mistakes: ['Relaxing at the bottom'],
  ),
  Exercise(
    id: 'split_squat', name: 'Split Squat', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 4, demo: 'split_squat', floorWork: false, kneeStress: true, perSide: true,
    family: 'squat',
    summary: 'A staggered-stance squat that builds single-leg strength.',
    cues: ['Take a long step, back heel lifted.',
      'Lower straight down until your back knee almost touches the floor.',
      'Keep your torso upright and front heel planted.',
      'Push through the front foot to rise. Finish one side, then switch.'],
    mistakes: ['Stance too short', 'Front knee collapsing inward'],
  ),
  Exercise(
    id: 'tempo_split_squat', name: 'Tempo Split Squat', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 5, demo: 'split_squat', floorWork: false, kneeStress: true, perSide: true,
    secondsPerRep: 5, family: 'squat',
    summary: 'Three seconds down, one second up — no furniture needed.',
    cues: ['Split stance, back heel up.',
      'Lower for a slow count of three.',
      'Pause just above the floor.',
      'Drive up in one second.'],
    mistakes: ['Rushing the lowering'],
  ),
  Exercise(
    id: 'bulgarian_split_squat', name: 'Bulgarian Split Squat', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 6, demo: 'bulgarian', props: {Prop.elevated}, floorWork: false, kneeStress: true,
    perSide: true, family: 'squat',
    summary: 'Rear foot on a bed, sofa or chair. A brutal single-leg builder.',
    cues: ['Stand a big step in front of a bed, sofa or chair and rest your rear foot on it.',
      'Lower until your front thigh is about parallel to the floor.',
      'Keep your weight in the front heel.',
      'Drive back up. Finish one side, then switch.'],
    mistakes: ['Front foot too close to the support', 'Pushing off the back foot'],
  ),
  Exercise(
    id: 'skater_squat', name: 'Skater Squat', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 7, demo: 'pistol', floorWork: false, kneeStress: true, perSide: true,
    family: 'squat',
    summary: 'Single-leg squat with the back knee lowering to a towel.',
    cues: ['Stand on one leg, the other bent behind you.',
      'Reach your arms forward and lower until the back knee touches a folded towel.',
      'Keep the standing heel down.',
      'Stand up without pushing off the back leg.'],
    mistakes: ['Dropping hard onto the knee'],
  ),
  Exercise(
    id: 'assisted_pistol_squat', name: 'Assisted Pistol Squat', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 8, demo: 'pistol', props: {Prop.wall}, floorWork: false, kneeStress: true,
    perSide: true, family: 'squat',
    summary: 'Pistol squat with a hand on the wall or door frame for balance.',
    cues: ['Stand side-on to a wall, one hand lightly on it.',
      'Lift one leg forward and squat down on the other.',
      'Use the wall only for balance, not to pull.',
      'Stand up tall.'],
    mistakes: ['Pulling on the wall'],
  ),
  Exercise(
    id: 'box_pistol_squat', name: 'Pistol to Box', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 9, demo: 'pistol', props: {Prop.elevated}, floorWork: false, kneeStress: true,
    perSide: true, family: 'squat',
    summary: 'Single-leg squat down to a chair or bed edge.',
    cues: ['Stand in front of a chair or bed on one leg.',
      'Reach forward and slowly sit to the edge.',
      'Touch lightly, don\'t rest.',
      'Stand up on one leg.'],
    mistakes: ['Crashing onto the seat'],
  ),
  Exercise(
    id: 'pistol_squat', name: 'Pistol Squat', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 10, demo: 'pistol', floorWork: false, kneeStress: true, perSide: true,
    family: 'squat',
    summary: 'The top of the leg path.',
    cues: ['Stand on one leg, arms forward, other leg straight out.',
      'Squat all the way down with control.',
      'Keep the standing heel down.',
      'Drive up without letting the knee cave.'],
    mistakes: ['Losing the heel', 'Bouncing out of the bottom'],
  ),
  Exercise(
    id: 'reverse_lunge', name: 'Reverse Lunge', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 3, demo: 'lunge', floorWork: false, kneeStress: true, perSide: true,
    summary: 'Step back into a lunge — kinder on the knees than forward lunges.',
    cues: ['Stand tall, feet hip-width.',
      'Step one foot back and lower until both knees bend to about 90°.',
      'Keep your front heel planted.',
      'Push through the front foot to return. Alternate legs.'],
    mistakes: ['Leaning far forward'],
  ),
  Exercise(
    id: 'lateral_lunge', name: 'Lateral Lunge', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 4, demo: 'lateral_lunge', floorWork: false, perSide: true, space: SpaceNeed.medium,
    summary: 'Side-to-side strength for hips and inner thighs.',
    cues: ['Take a wide step to the side.',
      'Sit back into that hip, keeping the other leg straight.',
      'Keep both feet flat and chest up.',
      'Push back to the centre.'],
    mistakes: ['Bent knee caving forward'],
  ),
  Exercise(
    id: 'curtsy_lunge', name: 'Curtsy Lunge', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 4, demo: 'lunge', floorWork: false, kneeStress: true, perSide: true,
    summary: 'Cross-behind lunge for the glutes.',
    cues: ['Step one leg diagonally behind the other.',
      'Lower until the front thigh is near parallel.',
      'Keep your hips facing forward.',
      'Return and alternate.'],
    mistakes: ['Twisting the hips'],
  ),
  Exercise(
    id: 'step_up', name: 'Step-up', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 4, demo: 'step_up', props: {Prop.elevated}, floorWork: false, perSide: true,
    summary: 'Step onto a sturdy, low surface. Use a bottom stair or a stable low box, never a wheeled chair.',
    cues: ['Place one whole foot on a low, stable step.',
      'Drive through that heel to stand up tall.',
      'Lower slowly with control.',
      'Finish one side, then switch.'],
    mistakes: ['Pushing off the bottom foot'],
  ),
  Exercise(
    id: 'wall_sit', name: 'Wall Sit', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 3, demo: 'wall_sit', props: {Prop.wall}, floorWork: false,
    unit: ExerciseUnit.seconds,
    summary: 'A burning isometric hold for the thighs.',
    cues: ['Lean your back against a wall.',
      'Slide down until your knees are about 90°.',
      'Keep your weight in your heels.',
      'Hold and breathe.'],
    mistakes: ['Hands pushing on the thighs'],
  ),
  Exercise(
    id: 'calf_raise', name: 'Calf Raise', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 1, demo: 'calf_raise', floorWork: false,
    summary: 'Strong ankles and calves.',
    cues: ['Stand tall near a wall for balance.',
      'Rise onto the balls of your feet as high as you can.',
      'Pause at the top.',
      'Lower slowly.'],
    mistakes: ['Bouncing'],
  ),
  Exercise(
    id: 'single_leg_calf_raise', name: 'Single-leg Calf Raise', area: Area.legs, pattern: MovementPattern.squat,
    focus: _legs, difficulty: 3, demo: 'calf_raise', floorWork: false, perSide: true,
    summary: 'Calf raise on one leg.',
    cues: ['Stand on one foot, fingertips on a wall.',
      'Rise as high as possible.',
      'Pause for a second.',
      'Lower all the way down.'],
    mistakes: ['Rushing the lowering'],
  ),
  Exercise(
    id: 'walking_lunge', name: 'Walking Lunge', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 4, demo: 'lunge', floorWork: false, kneeStress: true, space: SpaceNeed.large,
    summary: 'Travelling lunges — needs room to walk.',
    cues: ['Step forward into a lunge.',
      'Lower the back knee toward the floor.',
      'Drive up and step straight into the next lunge.',
      'Keep your torso tall.'],
    mistakes: ['Short steps'],
  ),
  Exercise(
    id: 'cossack_squat', name: 'Cossack Squat', area: Area.legs, pattern: MovementPattern.lunge,
    focus: _legs, difficulty: 6, demo: 'lateral_lunge', floorWork: false, perSide: true, space: SpaceNeed.medium,
    summary: 'A deep side squat that builds strength and mobility.',
    cues: ['Take a very wide stance.',
      'Squat deep to one side, the other leg straight with toes up.',
      'Keep the working heel down.',
      'Shift across to the other side.'],
    mistakes: ['Heel lifting'],
  ),

  // ───────────────────────────── HIPS / POSTERIOR ─────────────────────────────
  Exercise(
    id: 'glute_bridge', name: 'Glute Bridge', area: Area.legs, pattern: MovementPattern.hinge,
    focus: {MuscleFocus.legs, MuscleFocus.core}, difficulty: 1, demo: 'glute_bridge',
    summary: 'Wakes up the glutes and protects the lower back.',
    cues: ['Lie on your back, knees bent, feet flat and hip-width.',
      'Press through your heels and lift your hips.',
      'Squeeze your glutes hard at the top — ribs down.',
      'Lower slowly.'],
    mistakes: ['Arching the lower back instead of using the glutes'],
  ),
  Exercise(
    id: 'glute_bridge_march', name: 'Bridge March', area: Area.legs, pattern: MovementPattern.hinge,
    focus: {MuscleFocus.legs, MuscleFocus.core}, difficulty: 2, demo: 'glute_bridge', perSide: true,
    summary: 'Hold a bridge and march one knee up at a time.',
    cues: ['Lift into a glute bridge.',
      'Lift one foot a few centimetres without the hips dropping.',
      'Put it down and switch.',
      'Keep the hips level.'],
    mistakes: ['Hips tilting'],
  ),
  Exercise(
    id: 'b_stance_glute_bridge', name: 'B-stance Bridge', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 3, demo: 'glute_bridge', perSide: true,
    summary: 'One foot slightly forward so the other leg does most of the work.',
    cues: ['Set one foot a half-step forward on its heel.',
      'Drive through the back foot to bridge up.',
      'Squeeze at the top.',
      'Finish one side, then switch.'],
    mistakes: ['Pushing through the front foot'],
  ),
  Exercise(
    id: 'single_leg_glute_bridge', name: 'Single-leg Glute Bridge', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 4, demo: 'glute_bridge', perSide: true,
    summary: 'Bridge on one leg.',
    cues: ['One foot flat, the other leg straight or knee hugged.',
      'Drive through the planted heel.',
      'Keep your hips level at the top.',
      'Lower slowly.'],
    mistakes: ['Hips rotating'],
  ),
  Exercise(
    id: 'hip_thrust', name: 'Hip Thrust', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 5, demo: 'hip_thrust', props: {Prop.elevated},
    summary: 'Upper back on a sofa or bed edge for a bigger range than a bridge.',
    cues: ['Sit with your shoulder blades against a sofa or bed edge.',
      'Feet flat, knees bent.',
      'Drive your hips up until your torso is flat like a table.',
      'Chin tucked, squeeze, then lower.'],
    mistakes: ['Over-arching at the top'],
  ),
  Exercise(
    id: 'single_leg_rdl', name: 'Single-leg Hip Hinge', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 5, demo: 'single_leg_rdl', floorWork: false, perSide: true,
    summary: 'Balance and hamstring strength on one leg.',
    cues: ['Stand on one leg, knee soft.',
      'Hinge forward as your free leg reaches back, body like a seesaw.',
      'Keep your hips square to the floor.',
      'Squeeze the glute to stand tall.'],
    mistakes: ['Opening the hip toward the ceiling'],
  ),
  Exercise(
    id: 'single_leg_hip_thrust', name: 'Single-leg Hip Thrust', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 6, demo: 'hip_thrust', props: {Prop.elevated}, perSide: true,
    summary: 'Hip thrust on one leg.',
    cues: ['Upper back on the sofa or bed edge.',
      'One foot planted, the other knee pulled in.',
      'Drive the hips up level.',
      'Lower with control.'],
    mistakes: ['Hips twisting'],
  ),
  Exercise(
    id: 'hamstring_walkout', name: 'Hamstring Walkout', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 7, demo: 'glute_bridge',
    summary: 'Walk your heels out from a bridge — hard on the hamstrings.',
    cues: ['Lift into a glute bridge.',
      'Take small heel steps away from you while keeping the hips up.',
      'Go as far as you can control.',
      'Walk them back in.'],
    mistakes: ['Hips dropping as the feet walk out'],
  ),
  Exercise(
    id: 'towel_leg_curl', name: 'Towel Leg Curl', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 8, demo: 'leg_curl', props: {Prop.towel},
    summary: 'Heels on a towel on a smooth floor — slide in and out from a bridge.',
    cues: ['Lie on your back, heels on a towel on a smooth floor.',
      'Lift your hips into a bridge.',
      'Slide your heels out until your legs are nearly straight.',
      'Curl them back in while keeping the hips high.'],
    mistakes: ['Letting the hips drop'],
  ),
  Exercise(
    id: 'single_leg_towel_curl', name: 'Single-leg Towel Curl', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 9, demo: 'leg_curl', props: {Prop.towel}, perSide: true,
    summary: 'The top of the hip path.',
    cues: ['One heel on the towel, the other leg lifted.',
      'Bridge up and slide the heel out.',
      'Curl back in with the hips high.',
      'Finish one side, then switch.'],
    mistakes: ['Rushing'],
  ),
  Exercise(
    id: 'standing_glute_kickback', name: 'Standing Glute Kickback', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 1, demo: 'kickback', floorWork: false, perSide: true, warmup: true,
    summary: 'Glute activation without getting on the floor.',
    cues: ['Stand tall, hands on a wall.',
      'Kick one leg straight back, squeezing the glute.',
      'Don\'t arch your lower back.',
      'Return and repeat.'],
    mistakes: ['Swinging the leg'],
  ),
  Exercise(
    id: 'good_morning', name: 'Bodyweight Good Morning', area: Area.legs, pattern: MovementPattern.hinge,
    focus: _legs, difficulty: 2, demo: 'good_morning', floorWork: false, warmup: true,
    summary: 'Learn the hip hinge.',
    cues: ['Hands behind your head, feet hip-width, knees soft.',
      'Push your hips back as your chest tips forward.',
      'Keep a flat back and feel the hamstrings stretch.',
      'Squeeze your glutes to stand.'],
    mistakes: ['Rounding the back'],
  ),

  // ───────────────────────────── CORE ─────────────────────────────
  Exercise(
    id: 'dead_bug', name: 'Dead Bug', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 1, demo: 'dead_bug', perSide: true,
    summary: 'Teaches your abs to keep your back flat while your limbs move.',
    cues: ['Lie on your back, arms up, knees bent at 90° over your hips.',
      'Press your lower back into the floor.',
      'Slowly reach one arm back and the opposite leg out.',
      'Return and switch sides.'],
    mistakes: ['Lower back lifting off the floor'],
  ),
  Exercise(
    id: 'wall_plank', name: 'Wall Plank', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 1, demo: 'wall_push_up', props: {Prop.wall}, floorWork: false,
    unit: ExerciseUnit.seconds, family: 'plank',
    summary: 'A standing plank on a wall.',
    cues: ['Forearms on the wall, walk your feet back.',
      'Make a straight line from head to heels.',
      'Brace your abs as if bracing for a poke.',
      'Hold and breathe.'],
    mistakes: ['Hips sagging toward the wall'],
  ),
  Exercise(
    id: 'plank', name: 'Plank', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 2, demo: 'plank', unit: ExerciseUnit.seconds, family: 'plank',
    summary: 'The classic core hold.',
    cues: ['Forearms under shoulders, legs straight behind you.',
      'Squeeze glutes and pull your belly button in.',
      'Keep a straight line — no sagging, no piking.',
      'Breathe slowly and hold.'],
    mistakes: ['Hips sagging', 'Holding your breath'],
  ),
  Exercise(
    id: 'long_lever_plank', name: 'Long Plank', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 4, demo: 'plank', unit: ExerciseUnit.seconds, family: 'plank',
    summary: 'Elbows further forward than your shoulders — much harder on the abs.',
    cues: ['Start in a forearm plank.',
      'Walk your elbows forward a few centimetres past your head.',
      'Keep your hips level and ribs tucked.',
      'Hold.'],
    mistakes: ['Lower back arching'],
  ),
  Exercise(
    id: 'side_plank', name: 'Side Plank', area: Area.core, pattern: MovementPattern.coreLateral,
    focus: _core, difficulty: 4, demo: 'side_plank', unit: ExerciseUnit.seconds, perSide: true,
    summary: 'Builds the obliques and a stable waist.',
    cues: ['Lie on your side, elbow under your shoulder.',
      'Stack your feet and lift your hips.',
      'Make a straight line from head to feet.',
      'Hold, then switch sides.'],
    mistakes: ['Hips dropping backward'],
  ),
  Exercise(
    id: 'hollow_body_hold', name: 'Hollow Body Hold', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 6, demo: 'hollow_hold', unit: ExerciseUnit.seconds,
    summary: 'The gymnast\'s core foundation.',
    cues: ['Lie on your back and press your lower back into the floor.',
      'Lift your shoulders and legs a few centimetres.',
      'Reach your arms overhead (bend the knees to make it easier).',
      'Hold without the lower back lifting.'],
    mistakes: ['Lower back peeling off the floor'],
  ),
  Exercise(
    id: 'hollow_body_rock', name: 'Hollow Rock', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 7, demo: 'hollow_rock',
    summary: 'Rock back and forth in a hollow hold.',
    cues: ['Get into a hollow hold.',
      'Rock from your upper back to your hips as one unit.',
      'Keep the shape locked.',
      'Stop the set if the shape breaks.'],
    mistakes: ['Bending at the hips'],
  ),
  Exercise(
    id: 'v_up', name: 'V-up', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 8, demo: 'v_up',
    summary: 'Explosive full-range abs.',
    cues: ['Lie flat, arms overhead.',
      'Lift your legs and chest together to touch your toes.',
      'Lower slowly back to a hollow position.',
      'Don\'t fully relax between reps.'],
    mistakes: ['Using momentum to crash down'],
  ),
  Exercise(
    id: 'tuck_l_sit', name: 'Tuck L-sit', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: {MuscleFocus.core, MuscleFocus.arms}, difficulty: 9, demo: 'l_sit', wristStress: true,
    unit: ExerciseUnit.seconds,
    summary: 'Hands on the floor, lift your whole body with knees tucked.',
    cues: ['Sit with hands flat beside your hips.',
      'Press down hard and lift your hips off the floor.',
      'Pull your knees to your chest.',
      'Hold.'],
    mistakes: ['Shrugging shoulders to the ears'],
  ),
  Exercise(
    id: 'bicycle_crunch', name: 'Bicycle Crunch', area: Area.core, pattern: MovementPattern.coreRotation,
    focus: _core, difficulty: 3, demo: 'crunch', perSide: true,
    summary: 'Rotation for the obliques.',
    cues: ['Lie on your back, hands lightly behind your head.',
      'Bring one elbow toward the opposite knee while the other leg extends.',
      'Rotate from your ribs, not your neck.',
      'Alternate slowly.'],
    mistakes: ['Pulling on the neck'],
  ),
  Exercise(
    id: 'reverse_crunch', name: 'Reverse Crunch', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 3, demo: 'leg_raise',
    summary: 'Lower-ab focus by curling the hips up.',
    cues: ['Lie on your back, knees bent at 90° in the air.',
      'Curl your hips off the floor toward your chest.',
      'Lower slowly.',
      'Keep it controlled, no swinging.'],
    mistakes: ['Swinging the legs'],
  ),
  Exercise(
    id: 'leg_raise', name: 'Lying Leg Raise', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 5, demo: 'leg_raise',
    summary: 'Straight-leg raises for the lower abs.',
    cues: ['Lie flat, hands under your hips if needed.',
      'Keep your lower back pressed down.',
      'Raise your straight legs to vertical.',
      'Lower slowly, stopping before your back arches.'],
    mistakes: ['Back arching as the legs lower'],
  ),
  Exercise(
    id: 'flutter_kicks', name: 'Flutter Kicks', area: Area.core, pattern: MovementPattern.coreAnterior,
    focus: _core, difficulty: 4, demo: 'leg_raise', unit: ExerciseUnit.seconds,
    summary: 'Small fast kicks with the lower back glued down.',
    cues: ['Lie on your back, legs straight and slightly lifted.',
      'Kick small and quick.',
      'Keep your lower back down.',
      'Breathe steadily.'],
    mistakes: ['Legs too high to be useful'],
  ),
  Exercise(
    id: 'bird_dog', name: 'Bird Dog', area: Area.core, pattern: MovementPattern.coreRotation,
    focus: {MuscleFocus.core, MuscleFocus.back}, difficulty: 2, demo: 'bird_dog', perSide: true, kneeStress: true,
    summary: 'Spine-friendly core stability.',
    cues: ['On hands and knees, back flat.',
      'Reach one arm forward and the opposite leg back.',
      'Pause without rocking.',
      'Return and switch.'],
    mistakes: ['Arching the back'],
  ),
  Exercise(
    id: 'side_plank_hip_dip', name: 'Side Plank Hip Dip', area: Area.core, pattern: MovementPattern.coreLateral,
    focus: _core, difficulty: 5, demo: 'side_plank', perSide: true,
    summary: 'Dynamic side plank.',
    cues: ['Get into a side plank.',
      'Lower your hip toward the floor.',
      'Lift it back up higher than a straight line.',
      'Finish one side, then switch.'],
    mistakes: ['Rolling forward'],
  ),
  Exercise(
    id: 'russian_twist', name: 'Russian Twist', area: Area.core, pattern: MovementPattern.coreRotation,
    focus: _core, difficulty: 3, demo: 'crunch', perSide: true,
    summary: 'Rotational core with feet down or up.',
    cues: ['Sit leaning back slightly, chest up.',
      'Rotate your shoulders to one side, then the other.',
      'Move from your ribs, not just your arms.',
      'Lift your feet to make it harder.'],
    mistakes: ['Rounding the back'],
  ),
  Exercise(
    id: 'standing_knee_to_elbow', name: 'Standing Knee-to-Elbow', area: Area.core,
    pattern: MovementPattern.coreRotation, focus: _core, difficulty: 1, demo: 'march', floorWork: false,
    perSide: true, warmup: true,
    summary: 'Standing core work — no floor needed.',
    cues: ['Stand tall, hands behind your head.',
      'Lift one knee as you crunch the opposite elbow toward it.',
      'Stand tall again.',
      'Alternate sides.'],
    mistakes: ['Hunching the back instead of crunching'],
  ),
  Exercise(
    id: 'heel_taps', name: 'Heel Taps', area: Area.core, pattern: MovementPattern.coreLateral,
    focus: _core, difficulty: 2, demo: 'crunch', perSide: true,
    summary: 'Side-to-side oblique crunch.',
    cues: ['Lie on your back, knees bent, shoulders slightly lifted.',
      'Reach one hand to touch that heel.',
      'Switch sides.',
      'Keep the shoulders off the floor.'],
    mistakes: ['Dropping the head between reps'],
  ),
  Exercise(
    id: 'standing_side_crunch', name: 'Standing Side Crunch', area: Area.core, pattern: MovementPattern.coreLateral,
    focus: _core, difficulty: 1, demo: 'march', floorWork: false, perSide: true,
    summary: 'Lift a knee to the side while crunching the elbow down to it.',
    cues: ['Stand tall, hands behind your head.',
      'Lift one knee out to the side as the same-side elbow comes down.',
      'Squeeze the side of your waist.',
      'Return and repeat.'],
    mistakes: ['Leaning forward'],
  ),

  // ───────────────────────────── CONDITIONING ─────────────────────────────
  Exercise(
    id: 'march_in_place', name: 'March in Place', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 1, demo: 'march', floorWork: false, unit: ExerciseUnit.seconds, warmup: true,
    summary: 'Low-impact warm-up and conditioning.',
    cues: ['Stand tall.', 'Drive your knees up to hip height.', 'Swing your arms.', 'Keep a steady rhythm.'],
    mistakes: ['Slouching'],
  ),
  Exercise(
    id: 'step_jack', name: 'Step Jack', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 2, demo: 'jack', floorWork: false, unit: ExerciseUnit.seconds, warmup: true,
    summary: 'A jumping jack without the jump — quiet and joint-friendly.',
    cues: ['Step one foot out as your arms rise overhead.',
      'Step back in as your arms lower.',
      'Alternate sides.',
      'Speed up as you warm up.'],
    mistakes: ['Half-raising the arms'],
  ),
  Exercise(
    id: 'shadow_boxing', name: 'Shadow Boxing', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 3, demo: 'shadow_box', floorWork: false, unit: ExerciseUnit.seconds,
    summary: 'Low-impact cardio that works shoulders and core.',
    cues: ['Stand staggered, fists up by your chin.',
      'Throw fast straight punches, rotating through your hips.',
      'Stay light on your feet.',
      'Breathe out with each punch.'],
    mistakes: ['Locking the elbows hard'],
  ),
  Exercise(
    id: 'low_impact_skater', name: 'Low-impact Skater', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 3, demo: 'skater', floorWork: false, unit: ExerciseUnit.seconds,
    space: SpaceNeed.medium,
    summary: 'Side-to-side steps with a curtsy reach.',
    cues: ['Step wide to one side.',
      'Sweep the trailing leg behind you.',
      'Reach toward the front foot.',
      'Switch sides with rhythm.'],
    mistakes: ['Knee caving'],
  ),
  Exercise(
    id: 'speed_squat', name: 'Speed Squat', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.legs, MuscleFocus.fullBody}, difficulty: 4, demo: 'squat', floorWork: false,
    unit: ExerciseUnit.seconds, family: 'squat',
    summary: 'Fast, controlled squats for conditioning.',
    cues: ['Squat to a comfortable depth.', 'Stand up fast.', 'Keep your form clean.', 'Keep moving.'],
    mistakes: ['Sloppy depth'],
  ),
  Exercise(
    id: 'mountain_climber', name: 'Mountain Climber', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.core, MuscleFocus.fullBody}, difficulty: 4, demo: 'mountain_climber', wristStress: true,
    unit: ExerciseUnit.seconds,
    summary: 'Run in a plank.',
    cues: ['High plank, hands under shoulders.',
      'Drive one knee toward your chest, then switch fast.',
      'Keep your hips low.',
      'Stay on the balls of your feet.'],
    mistakes: ['Hips bouncing high'],
  ),
  Exercise(
    id: 'jumping_jack', name: 'Jumping Jack', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 4, demo: 'jack', floorWork: false, impact: true, unit: ExerciseUnit.seconds,
    summary: 'Classic cardio.',
    cues: ['Jump your feet out as your arms rise.', 'Jump back in as they lower.', 'Land softly.', 'Keep a rhythm.'],
    mistakes: ['Landing heavily'],
  ),
  Exercise(
    id: 'high_knees', name: 'High Knees', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 5, demo: 'march', floorWork: false, impact: true, unit: ExerciseUnit.seconds,
    summary: 'Sprint on the spot.',
    cues: ['Run in place, knees up to hip height.', 'Pump your arms.', 'Stay on the balls of your feet.', 'Go fast.'],
    mistakes: ['Leaning back'],
  ),
  Exercise(
    id: 'inchworm', name: 'Inchworm', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.fullBody, MuscleFocus.shoulders}, difficulty: 4, demo: 'burpee', wristStress: true,
    space: SpaceNeed.medium, warmup: true,
    summary: 'Walk your hands out to a plank and back.',
    cues: ['Stand tall, then hinge and place your hands on the floor.',
      'Walk your hands out to a high plank.',
      'Walk them back to your feet.',
      'Stand up.'],
    mistakes: ['Hips sagging in the plank'],
  ),
  Exercise(
    id: 'step_back_burpee', name: 'Step-back Burpee', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 5, demo: 'burpee', wristStress: true,
    summary: 'A burpee without jumping.',
    cues: ['Squat and place your hands on the floor.',
      'Step your feet back one at a time into a plank.',
      'Step them back in.',
      'Stand up and reach overhead.'],
    mistakes: ['Sagging plank'],
  ),
  Exercise(
    id: 'squat_jump', name: 'Squat Jump', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.legs, MuscleFocus.fullBody}, difficulty: 6, demo: 'squat_jump', floorWork: false,
    impact: true, kneeStress: true,
    summary: 'Explosive jumps for power and conditioning.',
    cues: ['Squat down.', 'Jump as high as you can.', 'Land softly back into the squat.', 'Reset and repeat.'],
    mistakes: ['Stiff-legged landings'],
  ),
  Exercise(
    id: 'burpee_no_push_up', name: 'Burpee (no push-up)', area: Area.conditioning,
    pattern: MovementPattern.conditioning, focus: _full, difficulty: 6, demo: 'burpee', impact: true,
    wristStress: true,
    summary: 'Squat, jump back to plank, jump in, jump up.',
    cues: ['Squat and put your hands down.', 'Jump your feet back to a plank.', 'Jump them back in.',
      'Jump up with arms overhead.'],
    mistakes: ['Hips sagging when landing in the plank'],
  ),
  Exercise(
    id: 'jumping_lunge', name: 'Jumping Lunge', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.legs}, difficulty: 7, demo: 'lunge', floorWork: false, impact: true, kneeStress: true,
    summary: 'Switch lunges in the air.',
    cues: ['Start in a lunge.', 'Jump and switch legs mid-air.', 'Land softly in a lunge.', 'Keep your torso tall.'],
    mistakes: ['Knee slamming the floor'],
  ),
  Exercise(
    id: 'burpee', name: 'Burpee', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 7, demo: 'burpee', impact: true, wristStress: true,
    summary: 'The full burpee with a push-up.',
    cues: ['Squat and put your hands down.', 'Jump back to a plank and do a push-up.',
      'Jump your feet in.', 'Jump up with arms overhead.'],
    mistakes: ['Skipping the push-up range'],
  ),
  Exercise(
    id: 'burpee_tuck_jump', name: 'Burpee Tuck Jump', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 9, demo: 'burpee', impact: true, wristStress: true, kneeStress: true,
    summary: 'The top of the conditioning path.',
    cues: ['Do a full burpee.', 'At the top, jump and pull your knees to your chest.', 'Land softly.',
      'Go straight into the next rep.'],
    mistakes: ['Hard landings'],
  ),
  Exercise(
    id: 'bear_crawl', name: 'Bear Crawl', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.fullBody, MuscleFocus.shoulders}, difficulty: 5, demo: 'bear_crawl', wristStress: true,
    kneeStress: true, space: SpaceNeed.medium, unit: ExerciseUnit.seconds,
    summary: 'Crawl with knees just off the floor.',
    cues: ['Hands under shoulders, knees under hips, knees hovering.',
      'Move opposite hand and foot together.',
      'Keep your back flat like a table.',
      'Go forward and back.'],
    mistakes: ['Hips high'],
  ),
  Exercise(
    id: 'skater_hop', name: 'Skater Hop', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.legs, MuscleFocus.fullBody}, difficulty: 6, demo: 'skater', floorWork: false,
    impact: true, space: SpaceNeed.medium, unit: ExerciseUnit.seconds,
    summary: 'Leap side to side like a speed skater.',
    cues: ['Leap sideways onto one foot.', 'Swing the other leg behind.', 'Land softly and stick it.',
      'Leap back.'],
    mistakes: ['Landing with a straight knee'],
  ),
  Exercise(
    id: 'shuttle_run', name: 'Shuttle Run', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: _full, difficulty: 6, demo: 'march', floorWork: false, impact: true, space: SpaceNeed.large,
    unit: ExerciseUnit.seconds,
    summary: 'Sprint between two points 5–10 m apart. Needs a big space or outdoors.',
    cues: ['Mark two points 5–10 metres apart.', 'Sprint to one, touch the ground.', 'Turn and sprint back.',
      'Keep going for the set time.'],
    mistakes: ['Wide, slow turns'],
  ),
  Exercise(
    id: 'plank_jack', name: 'Plank Jack', area: Area.conditioning, pattern: MovementPattern.conditioning,
    focus: {MuscleFocus.core, MuscleFocus.fullBody}, difficulty: 5, demo: 'mountain_climber', impact: true,
    wristStress: true, unit: ExerciseUnit.seconds,
    summary: 'Jumping jacks in a plank.',
    cues: ['High plank.', 'Jump your feet wide and back in.', 'Keep your hips level.', 'Stay tight.'],
    mistakes: ['Hips bouncing'],
  ),

  // ───────────────────────────── MOBILITY / RECOVERY / WARM-UP ─────────────────────────────
  Exercise(
    id: 'arm_circles', name: 'Arm Circles', area: Area.upper, pattern: MovementPattern.mobility,
    focus: {MuscleFocus.shoulders}, difficulty: 1, demo: 'arm_circles', floorWork: false,
    unit: ExerciseUnit.seconds, mobility: true, warmup: true,
    summary: 'Warm up the shoulders.',
    cues: ['Arms out to the sides.', 'Make small circles, getting bigger.', 'Reverse direction halfway.',
      'Stay relaxed.'],
  ),
  Exercise(
    id: 'leg_swings', name: 'Leg Swings', area: Area.legs, pattern: MovementPattern.mobility,
    focus: _legs, difficulty: 1, demo: 'leg_swing', floorWork: false, unit: ExerciseUnit.seconds, perSide: true,
    mobility: true, warmup: true,
    summary: 'Loosen the hips.',
    cues: ['Hold a wall for balance.', 'Swing one leg forward and back.', 'Gradually increase the range.',
      'Switch legs.'],
  ),
  Exercise(
    id: 'hip_circles', name: 'Hip Circles', area: Area.legs, pattern: MovementPattern.mobility,
    focus: _legs, difficulty: 1, demo: 'hip_circles', floorWork: false, unit: ExerciseUnit.seconds,
    mobility: true, warmup: true,
    summary: 'Warm up the hips and lower back.',
    cues: ['Hands on hips, feet wide.', 'Draw big slow circles with your hips.', 'Switch direction halfway.',
      'Keep your knees soft.'],
  ),
  Exercise(
    id: 'cat_cow', name: 'Cat-Cow', area: Area.core, pattern: MovementPattern.mobility,
    focus: {MuscleFocus.back, MuscleFocus.core}, difficulty: 1, demo: 'cat_cow', unit: ExerciseUnit.seconds,
    kneeStress: true, mobility: true, warmup: true,
    summary: 'Gentle spine mobility.',
    cues: ['On hands and knees.', 'Breathe in, drop your belly and lift your chest.',
      'Breathe out, round your back toward the ceiling.', 'Move slowly with your breath.'],
  ),
  Exercise(
    id: 'worlds_greatest_stretch', name: 'World\'s Greatest Stretch', area: Area.legs,
    pattern: MovementPattern.mobility, focus: _full, difficulty: 2, demo: 'stretch_lunge',
    unit: ExerciseUnit.seconds, perSide: true, mobility: true, warmup: true,
    summary: 'Hips, hamstrings and upper back in one move.',
    cues: ['Step into a deep lunge, hands on the floor.', 'Drop your inside elbow toward your front foot.',
      'Rotate and reach that arm to the ceiling.', 'Switch sides.'],
  ),
  Exercise(
    id: 'hip_flexor_stretch', name: 'Kneeling Hip Flexor Stretch', area: Area.legs, pattern: MovementPattern.mobility,
    focus: _legs, difficulty: 1, demo: 'stretch_lunge', unit: ExerciseUnit.seconds, perSide: true,
    kneeStress: true, mobility: true,
    summary: 'Opens the front of the hips.',
    cues: ['Kneel on one knee with a towel under it.', 'Tuck your pelvis and squeeze that glute.',
      'Shift forward gently until you feel the front of the hip stretch.', 'Breathe and hold.'],
  ),
  Exercise(
    id: 'standing_hamstring_stretch', name: 'Standing Hamstring Stretch', area: Area.legs,
    pattern: MovementPattern.mobility, focus: _legs, difficulty: 1, demo: 'good_morning', floorWork: false,
    unit: ExerciseUnit.seconds, perSide: true, mobility: true,
    summary: 'Hamstring stretch without the floor.',
    cues: ['Place one heel forward, toes up, knee straight.', 'Hinge at the hips with a flat back.',
      'Feel the back of the leg stretch.', 'Breathe and hold.'],
  ),
  Exercise(
    id: 'standing_quad_stretch', name: 'Standing Quad Stretch', area: Area.legs, pattern: MovementPattern.mobility,
    focus: _legs, difficulty: 1, demo: 'quad_stretch', floorWork: false, unit: ExerciseUnit.seconds,
    perSide: true, mobility: true,
    summary: 'Stretch the front of the thigh.',
    cues: ['Hold a wall for balance.', 'Pull one heel toward your glute.', 'Keep your knees together.',
      'Tuck the pelvis slightly and hold.'],
  ),
  Exercise(
    id: 'childs_pose', name: 'Child\'s Pose', area: Area.core, pattern: MovementPattern.mobility,
    focus: {MuscleFocus.back}, difficulty: 1, demo: 'childs_pose', unit: ExerciseUnit.seconds, kneeStress: true,
    mobility: true,
    summary: 'Rest and lengthen the back.',
    cues: ['Kneel and sit back toward your heels.', 'Reach your arms forward on the floor.',
      'Let your chest sink.', 'Breathe slowly into your back.'],
  ),
  Exercise(
    id: 'thoracic_rotation', name: 'Open Book Rotation', area: Area.upper, pattern: MovementPattern.mobility,
    focus: {MuscleFocus.back}, difficulty: 1, demo: 'open_book', unit: ExerciseUnit.seconds, perSide: true,
    mobility: true,
    summary: 'Upper back rotation lying on your side.',
    cues: ['Lie on your side, knees bent, arms straight in front.', 'Open the top arm across to the other side.',
      'Follow your hand with your eyes.', 'Return slowly. Switch sides halfway.'],
  ),
  Exercise(
    id: 'deep_squat_hold', name: 'Deep Squat Hold', area: Area.legs, pattern: MovementPattern.mobility,
    focus: _legs, difficulty: 2, demo: 'deep_squat', floorWork: false, unit: ExerciseUnit.seconds,
    mobility: true,
    summary: 'Sit in the bottom of a squat to open hips and ankles.',
    cues: ['Squat as deep as you comfortably can.', 'Push your knees out with your elbows.',
      'Keep your heels down (hold a door frame if needed).', 'Breathe and relax.'],
  ),
  Exercise(
    id: 'ankle_rocks', name: 'Ankle Rocks', area: Area.legs, pattern: MovementPattern.mobility,
    focus: _legs, difficulty: 1, demo: 'lunge', floorWork: false, unit: ExerciseUnit.seconds, perSide: true,
    mobility: true, warmup: true,
    summary: 'Improve ankle bend for better squats.',
    cues: ['Stand in a split stance near a wall.', 'Drive your front knee forward over your toes.',
      'Keep your heel down.', 'Rock in and out.'],
  ),
  Exercise(
    id: 'hip_90_90', name: '90/90 Hip Switch', area: Area.legs, pattern: MovementPattern.mobility,
    focus: _legs, difficulty: 2, demo: 'hip_90_90', unit: ExerciseUnit.seconds, mobility: true,
    summary: 'Rotate the hips through their range.',
    cues: ['Sit with both knees bent at 90°, one in front, one to the side.',
      'Rotate both knees to the other side.', 'Stay tall.', 'Move slowly.'],
  ),
  Exercise(
    id: 'chest_opener', name: 'Wall Chest Opener', area: Area.upper, pattern: MovementPattern.mobility,
    focus: {MuscleFocus.chest}, difficulty: 1, demo: 'wall_angel', props: {Prop.wall}, floorWork: false,
    unit: ExerciseUnit.seconds, perSide: true, mobility: true,
    summary: 'Stretch the chest after push work.',
    cues: ['Place your forearm on a wall at shoulder height.', 'Turn your body away gently.',
      'Feel the stretch across your chest.', 'Hold and switch sides.'],
  ),
  Exercise(
    id: 'box_breathing', name: 'Box Breathing', area: Area.core, pattern: MovementPattern.mobility,
    focus: _core, difficulty: 1, demo: 'breathing', floorWork: false, unit: ExerciseUnit.seconds,
    mobility: true,
    summary: 'Calm down and recover.',
    cues: ['Breathe in for 4 seconds.', 'Hold for 4.', 'Breathe out for 4.', 'Hold for 4. Repeat.'],
  ),
  Exercise(
    id: 'lying_hamstring_stretch', name: 'Lying Hamstring Stretch', area: Area.legs,
    pattern: MovementPattern.mobility, focus: _legs, difficulty: 1, demo: 'leg_raise',
    unit: ExerciseUnit.seconds, perSide: true, props: {Prop.towel}, mobility: true,
    summary: 'Use a towel around your foot to stretch the hamstring.',
    cues: ['Lie on your back, towel around one foot.', 'Raise the straight leg until you feel a stretch.',
      'Relax your shoulders.', 'Breathe and hold. Switch sides.'],
  ),
];

final Map<String, Exercise> kExerciseById = {for (final e in kExercises) e.id: e};

Exercise exerciseById(String id) {
  final e = kExerciseById[id];
  if (e == null) throw ArgumentError('Unknown exercise id: $id');
  return e;
}
