#!/usr/bin/env python3
"""Writes lib/bible/canon.g.dart from canon.py so the app and the data
pipeline share one book list."""

from pathlib import Path

import canon

OUT = Path(__file__).resolve().parent.parent.parent / "lib" / "bible" / "canon.g.dart"


def main() -> None:
    lines = [
        "// GENERATED by tools/bible_data/gen_dart_canon.py from canon.py.",
        "// Do not edit by hand.",
        "",
        "part of 'canon.dart';",
        "",
        "const _books = <BookInfo>[",
    ]
    for i, b in enumerate(canon.BOOKS):
        testament = "old" if b.testament == "OT" else "newT"
        lines += [
            "  BookInfo(",
            f"    index: {i},",
            f"    id: '{b.id}',",
            f"    name: '{b.name}',",
            f"    abbr: '{b.abbr}',",
            f"    testament: Testament.{testament},",
            f"    chapterCount: {b.chapters},",
            "  ),",
        ]
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
