package watch.cinex.app;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.pm.ActivityInfo;
import android.content.pm.ApplicationInfo;
import android.graphics.Bitmap;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.os.Message;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowInsets;
import android.view.WindowInsetsController;
import android.view.WindowManager;
import android.webkit.CookieManager;
import android.webkit.GeolocationPermissions;
import android.webkit.PermissionRequest;
import android.webkit.WebChromeClient;
import android.webkit.WebResourceRequest;
import android.webkit.WebResourceResponse;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;
import android.widget.FrameLayout;

import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * WebView wrapper for cinex.watch.
 *  - every popup / new window is dropped (native + injected JS), whatever its domain
 *  - top-level navigations and redirects off the allowlist are cancelled
 *  - requests to blocklisted (ad / popup) domains get an empty response
 *  - HTML5 fullscreen video and the back button are supported
 * Domain lists come from assets/domains.json (generated by scanner/build-lists.js). A debug build
 * also reads an override from getExternalFilesDir()/domains.json so tests can retest without a rebuild.
 */
public class MainActivity extends Activity {
    static final String TAG = "CinexGuard";
    private static final Pattern MEDIA = Pattern.compile("\\.(m3u8|mpd|mp4|m4s|webm|ts)(\\?|#|$)", Pattern.CASE_INSENSITIVE);

    private final Set<String> allow = new HashSet<>();
    private final Set<String> block = new HashSet<>();
    private String homeUrl = "https://cinex.watch/";

    private WebView web;
    private FrameLayout root;
    private View customView;
    private WebChromeClient.CustomViewCallback customViewCallback;

    @SuppressLint("SetJavaScriptEnabled")
    @Override
    protected void onCreate(Bundle state) {
        super.onCreate(state);
        loadConfig();
        boolean debuggable = (getApplicationInfo().flags & ApplicationInfo.FLAG_DEBUGGABLE) != 0;
        WebView.setWebContentsDebuggingEnabled(debuggable);

        root = new FrameLayout(this);
        root.setBackgroundColor(Color.BLACK);
        web = new WebView(this);
        web.setBackgroundColor(Color.BLACK);
        root.addView(web, new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        setContentView(root);

        WebSettings s = web.getSettings();
        s.setJavaScriptEnabled(true);
        s.setDomStorageEnabled(true);
        s.setDatabaseEnabled(true);
        s.setMediaPlaybackRequiresUserGesture(false);
        // Multiple windows ON + onCreateWindow returning false = every new window is simply dropped.
        // (With it OFF, WebView would load target=_blank / window.open in this same window.)
        s.setSupportMultipleWindows(true);
        s.setJavaScriptCanOpenWindowsAutomatically(false);
        s.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);
        s.setLoadWithOverviewMode(true);
        s.setUseWideViewPort(true);
        s.setUserAgentString(s.getUserAgentString().replace("; wv)", ")"));
        CookieManager.getInstance().setAcceptCookie(true);
        CookieManager.getInstance().setAcceptThirdPartyCookies(web, true);

        String guard = guardJs();
        boolean docStart = WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT);
        if (docStart) {
            // Runs before any page script, in the main frame AND every iframe.
            WebViewCompat.addDocumentStartJavaScript(web, guard, Collections.singleton("*"));
        }

        web.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, WebResourceRequest req) {
                Uri u = req.getUrl();
                String scheme = u.getScheme() == null ? "" : u.getScheme().toLowerCase();
                if (!scheme.equals("http") && !scheme.equals("https")) {
                    Log.i(TAG, "BLOCKED_SCHEME " + u);           // intent://, market://, tg:// ...
                    return true;
                }
                if (!req.isForMainFrame()) return false;
                if (isAllowed(u.getHost())) return false;
                Log.i(TAG, "BLOCKED_NAV " + u.getHost() + (req.isRedirect() ? " (redirect)" : "") + " " + u);
                return true;
            }

            @Override
            public WebResourceResponse shouldInterceptRequest(WebView view, WebResourceRequest req) {
                String host = req.getUrl().getHost();
                if (isBlocked(host) && !isAllowed(host)) {
                    Log.i(TAG, "BLOCKED_REQ " + host);
                    return new WebResourceResponse("text/plain", "utf-8", new ByteArrayInputStream(new byte[0]));
                }
                if (req.isForMainFrame() && !isAllowed(host)) {
                    // Last line of defence for navigations that bypass shouldOverrideUrlLoading.
                    Log.i(TAG, "BLOCKED_NAV " + host + " (intercept)");
                    return new WebResourceResponse("text/html", "utf-8", new ByteArrayInputStream(new byte[0]));
                }
                if (MEDIA.matcher(req.getUrl().getPath() == null ? "" : req.getUrl().getPath()).find()) {
                    Log.i(TAG, "MEDIA " + host);
                }
                return null;
            }

            @Override
            public void onPageStarted(WebView view, String url, Bitmap favicon) {
                if (!docStart) view.evaluateJavascript(guard, null);
            }

            @Override
            public boolean onRenderProcessGone(WebView view, android.webkit.RenderProcessGoneDetail detail) {
                Log.w(TAG, "renderer gone, recreating");
                recreate();
                return true;
            }
        });

        web.setWebChromeClient(new WebChromeClient() {
            @Override
            public boolean onCreateWindow(WebView view, boolean isDialog, boolean isUserGesture, Message resultMsg) {
                WebView.HitTestResult hit = view.getHitTestResult();
                Log.i(TAG, "BLOCKED_POPUP " + (hit != null ? hit.getExtra() : ""));
                return false;
            }

            @Override
            public void onShowCustomView(View view, CustomViewCallback callback) {
                if (customView != null) { callback.onCustomViewHidden(); return; }
                customView = view;
                customViewCallback = callback;
                root.addView(view, new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
                web.setVisibility(View.GONE);
                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);
                setFullscreenUi(true);
                Log.i(TAG, "FULLSCREEN_ON");
            }

            @Override
            public void onHideCustomView() { exitFullscreen(); }

            @Override
            public Bitmap getDefaultVideoPoster() {
                return Bitmap.createBitmap(1, 1, Bitmap.Config.ARGB_8888); // no grey play-icon placeholder
            }

            @Override
            public void onPermissionRequest(PermissionRequest request) { request.deny(); }

            @Override
            public void onGeolocationPermissionsShowPrompt(String origin, GeolocationPermissions.Callback cb) { cb.invoke(origin, false, false); }
        });

        if (state != null) web.restoreState(state);
        else web.loadUrl(homeUrl);
    }

    private void exitFullscreen() {
        if (customView == null) return;
        root.removeView(customView);
        customView = null;
        web.setVisibility(View.VISIBLE);
        if (customViewCallback != null) customViewCallback.onCustomViewHidden();
        customViewCallback = null;
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
        setFullscreenUi(false);
        Log.i(TAG, "FULLSCREEN_OFF");
    }

    @SuppressWarnings("deprecation")
    private void setFullscreenUi(boolean on) {
        if (android.os.Build.VERSION.SDK_INT >= 30) {
            WindowInsetsController c = getWindow().getInsetsController();
            if (c == null) return;
            if (on) {
                c.hide(WindowInsets.Type.systemBars());
                c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
            } else {
                c.show(WindowInsets.Type.systemBars());
            }
        } else {
            getWindow().getDecorView().setSystemUiVisibility(on
                    ? View.SYSTEM_UI_FLAG_FULLSCREEN | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
                    | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                    : 0);
        }
        if (on) getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
        else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
    }

    @SuppressWarnings("deprecation")
    @Override
    public void onBackPressed() {
        if (customView != null) exitFullscreen();
        else if (web.canGoBack()) web.goBack();
        else super.onBackPressed();
    }

    @Override protected void onPause() { super.onPause(); web.onPause(); }
    @Override protected void onResume() { super.onResume(); web.onResume(); }
    @Override protected void onSaveInstanceState(Bundle out) { super.onSaveInstanceState(out); web.saveState(out); }
    @Override protected void onDestroy() { web.destroy(); super.onDestroy(); }

    // ---------------------------------------------------------------- domain lists

    boolean isAllowed(String host) { return matches(host, allow); }
    boolean isBlocked(String host) { return matches(host, block); }

    /** host equals a listed domain or is a subdomain of it. */
    static boolean matches(String host, Set<String> set) {
        if (host == null) return false;
        String h = host.toLowerCase();
        while (true) {
            if (set.contains(h)) return true;
            int dot = h.indexOf('.');
            if (dot < 0) return false;
            h = h.substring(dot + 1);
        }
    }

    private void loadConfig() {
        try {
            JSONObject cfg = new JSONObject(read(getAssets().open("domains.json")));
            File override = new File(getExternalFilesDir(null), "domains.json");
            boolean debuggable = (getApplicationInfo().flags & ApplicationInfo.FLAG_DEBUGGABLE) != 0;
            if (debuggable && override.exists()) {
                cfg = new JSONObject(read(new FileInputStream(override)));
                Log.i(TAG, "using override config " + override);
            }
            addAll(cfg.optJSONArray("allow"), allow);
            addAll(cfg.optJSONArray("manualAllow"), allow);
            addAll(cfg.optJSONArray("block"), block);
            String own = cfg.optString("ownDomain", "cinex.watch");
            allow.add(own);
            homeUrl = "https://" + own + "/";
        } catch (Exception e) {
            Log.e(TAG, "config error, using defaults", e);
            allow.add("cinex.watch");
        }
        Log.i(TAG, "allow=" + allow + " block=" + block.size());
    }

    private static void addAll(JSONArray a, Set<String> into) {
        if (a == null) return;
        for (int i = 0; i < a.length(); i++) into.add(a.optString(i).toLowerCase());
    }

    private static String read(InputStream in) throws java.io.IOException {
        try (InputStream is = in) {
            java.io.ByteArrayOutputStream out = new java.io.ByteArrayOutputStream();
            byte[] buf = new byte[8192];
            for (int n; (n = is.read(buf)) > 0; ) out.write(buf, 0, n);
            return out.toString(StandardCharsets.UTF_8.name());
        }
    }

    /** JS injected at document start in every frame: kills window.open and new-window links. */
    private String guardJs() {
        return "(function(){if(window.__cxg)return;window.__cxg=1;"
                + "var A=" + new JSONArray(allow) + ";"
                + "function ok(u){try{var h=new URL(u,location.href).hostname;return A.some(function(d){return h===d||h.endsWith('.'+d)})}catch(e){return false}}"
                + "var dead=function(){return{closed:true,close:function(){},focus:function(){},blur:function(){},postMessage:function(){},"
                + "document:{write:function(){},open:function(){},close:function(){}},location:{href:'',replace:function(){},assign:function(){}}}};"
                + "try{Object.defineProperty(window,'open',{value:dead,writable:false,configurable:false})}catch(e){window.open=dead}"
                + "function newWin(t){return t&&!/^_(self|parent|top)$/i.test(t)}"
                // target=_blank links: same-site ones open in place (top frame only), everything else is swallowed
                + "function guard(e){var a=e.target&&e.target.closest&&e.target.closest('a[target],area[target]');"
                + "if(a&&newWin(a.target)){e.preventDefault();e.stopImmediatePropagation();if(window===top&&ok(a.href))location.href=a.href}}"
                + "document.addEventListener('click',guard,true);document.addEventListener('auxclick',guard,true);"
                + "var ac=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(newWin(this.target))return;return ac.apply(this,arguments)};"
                + "document.addEventListener('submit',function(e){if(newWin(e.target.target))e.preventDefault()},true);"
                + "})();";
    }
}
